### ISSUE TITLE
service registration - disable file delete when service registration is in-progress

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1008]
Currently the user can delete the file even when the service registration is in-progress. This must be disabled when the service registration request in-progress. 
Same must be implemented also in update service component. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/d0a2c195-6492-43af-ba92-bfa9b094802a)

**Comment by WangLiNaruto** [comment]
let me do it
