### ISSUE TITLE
update request URI for end user credentials management

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1009]
To ensure uniformity of URIs, we must update the URIs for end user's credentials management to /xpanse/credentials/user for all 4 methods. 

- [ ] update URI
- [ ] update API in UI with new URI changes.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/952ed5bb-4863-4623-943c-922ace2a9b4c)

**Comment by WangLiNaruto** [comment]
Let me do it
