### ISSUE TITLE
When deployment failed the deployed resources will not be destroyed.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1023]
When deployment failed  caused  by the terraform command error,  the `resources` in the `deployResult`  is always empty  and the deployed resources will not be destroyed. We should remove judgment condition and always execute the destroy when the deployment failed.  The logic in terraform-boot should be checked  also.

![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/cee2eccb-eeed-4511-a6c6-9a8406530036)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/a19d0738-5b7e-4306-a461-f174da877727)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/5deb2e8b-977b-4ee2-b464-a58ed5d0339a)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/d25a3a4f-69f3-4569-91f0-129f787a2d9f)

**Comment by baixinsui** [comment]
I will fix it.

**Comment by swaroopar** [comment]
Thank you @baixinsui
