### ISSUE TITLE
Create new end user service -> getVendorHostedServiceDetailsById

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1025]
- [ ] Create new data model -> VendorHostedServiceDetailsVo
- [ ] Extends ServiceVo.
- [ ] Similar to ServiceDetailVo but must not have resultMessage, deployResources
- [ ] Method returns only services whose service hosting type is -> SERVICE_VENDOR. If the service is called with the ID of the self-hosted service, return 404 NOT_FOUND

**Comment by WangLiNaruto** [comment]
let me do it
