### ISSUE TITLE
Add Reports page to ISV role

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1027]
Similar to end user MyServices page of end user, we need to display all services that are deployed and belongs to the same  namespace as of the ISV user. 

- [ ] Menu name should be "Reports"
- [ ] Table should be same as MyServices -> with only "details" option. 
- [ ] details button must be enabled only when the service hosted by service vendor. 

Depends on #1024

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
I'll take this
