### ISSUE TITLE
remove react-query passed as component properties

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1029]
In the credential components, the queries are passed as component properties. This must be removed. 

https://github.com/eclipse-xpanse/xpanse-ui/blob/main/src/components/content/credential/AddCredential.tsx#L31 

- [ ] Move all shared queries as custom query hooks and then directly used it in components. 
- [ ] To be checked and fixed in all credential related components.

**Comment by WangLiNaruto** [comment]
let me do it
