### ISSUE TITLE
MyServices - use different methods to get service details based on service hosting type

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1034]
based on the type of the service hosting used by the service, different API methods must be used to load service details. 

1. In case of self-hosted, use getSelfHostedServiceDetailsById
2. In case of service-vendor hosted, use getVendorHostedServiceDetailsById 

dependent on #1026

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
implemented.
