### ISSUE TITLE
incorrect response returned when terraform-boot is not reachable

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1039]
When terraform-boot service is not reachable, we must return TerraformBootRequestFailedException with errorcode 500. 

Currently we return HTTP 500 with generic error -

11:14:08.932 [http-nio-8080-exec-8] INFO  o.e.x.m.logging.CustomHttpLogWriter [cae7e2f4-fe27-46d1-8d1e-6f8d501c4d4a]- Response: 500 Internal Server Error Duration: 267ms  {"resultType":"Runtime Error","details":["I/O error on POST request for \"http://localhost:9090/terraform-boot/validate/scripts\": Connection refused"],"success":false}

**Comment by WangLiNaruto** [comment]
let me do it
