### ISSUE TITLE
TerraformBoot callback APIs of Xpanse retruns unexpected authentication exception.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1042]
TerraformBoot callback APIs of Xpanse retruns unexpected authentication exception.
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/ab0ffe48-4e5d-47f1-98ec-80071fb36b28)
Caused by: In the callback the method `identityProviderManager.getCurrentLoginUserId()` but the TerraformBoot client provided any authentication information
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/b3d2745b-41a0-4243-9f13-58f336df9216)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/137eb9d4-a902-480c-9ed5-a19229f04b81)

Please add integration testing for the `WebhookApi` to avoid the same problem

**Comment by baixinsui** [comment]
@swaroopar When the `TerraformBoot` is enabled, the UUID of  `taskId` 、the workspace of terraform scripts and the UUID in the output log  in the `TerrraformBoot` are all different. Why don't we use the same ID as `TerraformLocal`

**Comment by swaroopar** [comment]
> @swaroopar When the `TerraformBoot` is enabled, the UUID of `taskId` 、the workspace of terraform scripts and the UUID in the output log in the `TerrraformBoot` are all different. Why don't we use the same ID as `TerraformLocal`

@baixinsui it is a different topic. Let us discuss it separately.

**Comment by swaroopar** [comment]
@WangLiNaruto looks like one more usecase that is broken after our recent changes.

**Comment by baixinsui** [comment]
> > @swaroopar When the `TerraformBoot` is enabled, the UUID of `taskId` 、the workspace of terraform scripts and the UUID in the output log in the `TerrraformBoot` are all different. Why don't we use the same ID as `TerraformLocal`
> 
> @baixinsui it is a different topic. Let us discuss it separately.

ok
