### ISSUE TITLE
When TerraformBoot enables authentication, Xpanse calls its APIs always return  401 unauthenticated exception.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1043]
When TerraformBoot enables authentication, Xpanse calls its APIs always return  401 unauthenticated exception.
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/a5b775f8-4e60-4ddd-b904-3bc952ccabc3)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/09365d05-32b6-474e-9ea4-e3733ca40b61)

**Comment by WangLiNaruto** [comment]
let me do it
