### ISSUE TITLE
update policy API fails when the policy is enabled or disabled

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1051]
When the policy is only enabled or disabled, the updatePolicy API rejects the request with PolicyDuplicateException exception.

Update must be allowed to only enable or disable the policy.

**Comment by baixinsui** [comment]
I haven't reproduced this issue. 
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/93b937e3-7450-4091-9d70-decbba35221d)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/f512e313-2dd4-4681-9fc6-1f2c0f1753a8)

![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/ccaf4c75-c07d-4753-a3e6-d3ef770bf602)
According to code logic,  the value of filed `enabled` changes will not call the method for checking for duplicates unless the value of `csp` or `policy` changes.

**Comment by swaroopar** [comment]
@baixinsui you are right. Even i'm not able to reproduce this issue anymore. Will close this issue for now. Thank you for checking.
