### ISSUE TITLE
MyServices table too big

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1054]
Currently the MyServices table is too big and we must change the "Operation" column to make sure the data columns are correctly displayed. 

Looking at other UIs, we must make two changes - use icons where possible and rest we can move under dropdown.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/01ce1475-a5e5-43d0-883c-7ce494670257)

**Comment by Alice1319** [comment]
I'll take this
