### ISSUE TITLE
Remove 'Vo' from model names

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1057]
To keep model names more self-explanatory, we must remove 'Vo' in the names. The model names must be renamed as follows

- [ ] PolicyVo -> Policy
- [ ] ServiceDetailVo -> DeployedServiceDetails
- [ ] ServiceVo -> DeployedService
- [ ] VendorHostedServiceDetailsVo -> VendorHostedDeployedServiceDetails

**Comment by WangLiNaruto** [comment]
let me do it
