### ISSUE TITLE
fix URIs for service details  related services

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1063]
getSelfHostedServiceDetailsById -> /services/details/self_hosted/{id}
getVendorHostedServiceDetailsById -> /services/details/vendor_hosted/{id}
getServiceDetailsByIdForIsv -> /services/isv/details/vendor_hosted/${id}
listDeployedServicesOfIsv -> /services/isv

update UI client.

**Comment by WangLiNaruto** [comment]
let me do it
