### ISSUE TITLE
control size of service details popover

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1076]
Some service details popover are rendered too big - current example is the SSH keys. 

We must handle it so that the pop over is not too big. Instead we must use scroll bars and also increase the length more and keep the width lesser. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/66f0ca42-7ca7-4980-9171-dad947c10571)

**Comment by Alice1319** [comment]
I’take this
