### ISSUE TITLE
remove async threads when terraform-boot is activated

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1078]
In order to avoid unnecessary handling of services and to have better tracing, we must remove the async thread created when terraform-boot is activated. 

All steps including the deployment and destroy request must be handled with in the sync http request.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by WangLiNaruto** [comment]
let me do it
