### ISSUE TITLE
handle new failure status - ROLLBACK_FAILED

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1092]
- [ ] In the new order and migration order, the status polling must be updated to handle the newly order status - ROLLBACK_FAILED
      ROLLBACK_FAILED must be treated similar to DEPLOYMENT_FAILED
      Eg - https://github.com/eclipse-xpanse/xpanse-ui/blob/main/src/components/content/order/create/OrderSubmitStatusPolling.tsx

- [ ] MyServices options - destroy and purge also be handled in the same way as DEPLOYMENT_FAILED.

**Comment by Alice1319** [comment]
I'll take this.
