### ISSUE TITLE
add more options to handle errors in service registration 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1099]
- [ ] Current option 'Try Again' -> Should retry the registration API request. Ensure the state in URL is correctly handled
- [ ] Add new option 'Upload New File' -> Should have the old behavior of 'Try Again'.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/9f2c8eda-e452-4370-9611-7984f214646d)

**Comment by Alice1319** [comment]
I'll take this
