### ISSUE TITLE
provide option to start-stop services on the UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1141]
- [ ] Display status of the service in the MyServices table -> If the status is running -> show it in green and an option to stop it next to it. 
![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/f46649a5-a29a-42c8-9719-d5016f751818)
- [ ] If the status is stopped -> show the status as 'stopped' with a run icon next to it to start the service.
- [ ] in case in case of STARTING -> show the 'starting' with stop icon as disabled
- [ ] in case of STOPPING -> show 'stopping' with start icon as disabled
- [ ] in case of STARTING_FAILED -> keep the run button enabled. 
- [ ] in case of STOPPING Failed -> keep the stopping button enabled.

**Comment by WangLiNaruto** [comment]
let me do it
