### ISSUE TITLE
replace http client from java-sdk-core in flexbileEngine plugin

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1168]
Currently the flexible engine plugin uses the http client from java-sdk-core and this must be replaced and we must use our own http client. 

- [ ] create http client using spring rest client. 
- [ ] write the request signer logic. 
- [ ] remove all dependencies to java-sdk-core from SBOM.

**Comment by baixinsui** [comment]
I will take it.
