### ISSUE TITLE
details option for vendor hosted services to be optionally enabled

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1171]
For end user role, the details option must be only conditionally enabled. Currently it is always enabled and we just display empty popup as below. 

- [x] It must be enabled when service details are available. 
- [x] It must be disabled if service details are not available and provide the following text on mouse over -> 'Please contact the service provider'

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/db72add1-4b5c-4256-8955-96210f2448c9)

**Comment by WangLiNaruto** [comment]
let me do it
