### ISSUE TITLE
provide refresh option always on all tables when the data loading fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1174]
Similar to the screenshot below, all tables in Xpanse UI must provide an option to refresh data even when the data loading fails. 
![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/433ad456-ec23-4224-9f3c-f7a2770652ff)

- [ ] MyServices, Polices, Service Policies - Refresh buttons to be always available.

**Comment by Alice1319** [comment]
I'll take this.
