### ISSUE TITLE
service migration - service entered to DB too late

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1197]
As part of the  service migration process, we are currently creating the service ID entry in the DB only at the `MigrateDeployProcess` step.  This is not correct because if the workflow fails in the steps before this, then we do not have any way to track this ID. 

- [ ] Create the entry in DB as part of the migrate API request itself. 
- [ ] Start the deployment as part of `MigrateDeployProcess` step.

**Comment by Alice1319** [comment]
I'll take this.

**Comment by WangLiNaruto** [comment]
let me do it
