### ISSUE TITLE
add new component to show workflow tasks assigned to user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1233]
- [ ] create new page "workflows"
- [ ] It must contain a table  with coloumns from WorkflowTask data -> processInstanceName, process instance ID, status -> done, failed, for failed -> provide a new option with drop down -> retry order, close order 
- [ ] Get all tasks of user from the below two APIs
https://app.swaggerhub.com/apis/eclipse-xpanse-bot/XpanseRuntimeApi/1.0.7#/Workflow/queryTodoTasks and https://app.swaggerhub.com/apis/eclipse-xpanse-bot/XpanseRuntimeApi/1.0.7#/Workflow/queryDoneTasks
- [ ] retry and close must be handled using https://app.swaggerhub.com/apis/eclipse-xpanse-bot/XpanseRuntimeApi/1.0.7#/WorkFlow/manageFailedOrder order.

**Comment by Alice1319** [comment]
I'll take this

**Comment by WangLiNaruto** [comment]
let me do it
