### ISSUE TITLE
Create new entity to store migration order data

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1235]
- [x] Create new DB table `SERVICE_MIGRATION`
- [x] Columns - MIGRATION_ID, OLD_SERVICE_ID, NEW_SERVICE_ID, MIGRATION_STATUS, USER_ID
- [x] `MigrationStatus` Enum -> MIGRATION_STARTED, DATA_EXPORT_STARTED,  DATA_EXPORT_FAILED,  DATA_EXPORT_COMPLETED,  DATA_IMPORT_STARTED, DATA_IMPORT_FAILED, DATA_IMPORT_COMPLETED, DESTROY_STARTED, DESTROY_FAILED, DESTROY_COMPLETED, DEPLOY_STARTED, DEPLOY_FAILED, DEPLOY_COMPLETED, MIGRATION_COMPLETED, MIGRATION_FAILED
- [ ] Insert the entry as part of the 'migrate' API request
- [ ] Update status at the beginning and end of each phase.

**Comment by WangLiNaruto** [comment]
let me do it
