### ISSUE TITLE
update queryTodoTasks and queryDoneTasks methods with authorization

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1237]
For both  queryTodoTasks and queryDoneTasks  API methods, 

- [ ] throw 403 AccessDeniedException exception when no user ID is found in the request context. 
- [ ] When the userId does not match the user who requested the migration request, also throw AccessDeniedException

**Comment by Alice1319** [comment]
I’ll take this

**Comment by WangLiNaruto** [comment]
let me do it
