### ISSUE TITLE
add openTofu as a new deployer

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1247]
Since OpenTofu 1.6 is now GA, we can now implement OpenTofu as a "deployer" type in addition to "terraform".

- [ ] Add new package `opentofu` under `deployment` maven module.
- [ ] Extend DeployerKind enum with OPEN_TOFU (opentofu)
- [ ] Implement functionality similar to "terraform-local".
- [ ] Move all common SystemCmd classes to `common` package.
- [ ] Test existing sample files using opentofu. 

Note - After this, we will also implement an application for opentofu similar to terraform-boot.

**Comment by baixinsui** [comment]
I will take it.
