### ISSUE TITLE
implement flavor specific service policies

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1261]
Currently service policies are at service level. This must be extend to allow CSPs to have common policies at service level and additional policies at flavor level. 

- [ ] Extend the data model to provide an optional "flavor_name" field for service policies. 
- [ ] if flavor name provided during policy creation, validate if the flavor name is valid, if not return the existing `FlavorInvalidException` exception. 
- [ ] If flavor name is not provided, then the policy is always executed during service deployment. 
- [ ] If flavor name is provided, then this policy is validated only if the service was ordered for that specific flavor.

**Comment by baixinsui** [comment]
I will take it.
