### ISSUE TITLE
add flavor to service policies in UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1274]
As part of the https://github.com/eclipse-xpanse/xpanse/issues/1261, service policies were used extended with an optional "flavor" field. 

- [ ] extend the service policies table with flavor column
- [ ] in modal for service policy creation, add a new optional drop down field -> values filled with flavor names of the service. By default the drop down should have empty value. 
- [ ] If flavor is selected, then this must be sent in the policy creation request.

**Comment by Alice1319** [comment]
I’ll take this.
