### ISSUE TITLE
update service migrate ui 

### ISSUE THREAD

**Issue by WangLiNaruto** [eclipse-xpanse/xpanse#1283]
Modify the page problem during migration. Due to the modification of the return value of the migrate interface, when querying under deployment status polling during migration, the process id query is used, and the following error occurs.
![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/ead0abf6-2ef3-4ce9-9240-504ca32af93d)

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
Hi @WangLiNaruto ,
For the migrate order, the polling must be completely switched to "getMigrationOrderDetailsById"
