### ISSUE TITLE
When the service is purged, the prompt information on the service list page does not display.

### ISSUE THREAD

**Issue by WangLiNaruto** [eclipse-xpanse/xpanse#1284]
When the service is purged, the prompt information on the service list page does not display.
![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/432aa75d-e099-4c51-9a12-475e00cb1824)

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
handled differently in  https://github.com/eclipse-xpanse/xpanse-ui/pull/439
