### ISSUE TITLE
add serviceProviderContactDetails for deploy service.

### ISSUE THREAD

**Issue by Alice1319** [eclipse-xpanse/xpanse#1308]

**Comment by n-keerthi-gayathri** [comment]
@swaroopar please assign me this issue

**Comment by swaroopar** [comment]
> @swaroopar please assign me this issue

@n-keerthi-gayathri Thanks for your interest. This topic is already picked up by the team. Meanwhile before considering contributing to the eclipse-xpanse repo, could you please read the contributing guidelines and send me your eclipse foundation account link please.

**Comment by Alice1319** [comment]
I’ll fix this.

**Comment by n-keerthi-gayathri** [comment]
Hello Swaroop,

I trust this message finds you well. My name is Keerthi Gayathri
Nissankararao, and I am an enthusiast of open-source contributions. I have
recently created an account on the Eclipse Foundation. Here is the link to
my account: nkeerthigayathri | Eclipse - The Eclipse Foundation open source
community website. <https://accounts.eclipse.org/users/nkeerthigayathri>.

Thank you for your time, and I look forward to engaging with the Eclipse
Foundation community.

Best regards,
Keerthi Gayathri Nissankararao
