### ISSUE TITLE
show the lastStartedAt and lastStoppedAt time in MyServices

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1312]
in the UI, we must show show the lastStartedAt and lastStoppedAt time

- [ ] within the service state column, time must be shown in a small grey color text. 
- [ ] if the service state is running -> then we show the time as "running since - xxxxxx"
- [ ] if the service state is stopped ->then show the time as "stopped at - xxxxx"

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
@WangLiNaruto please work on this after the https://github.com/eclipse-xpanse/xpanse-ui/pull/469 is merged. This has some latest fixes.
