### ISSUE TITLE
Extend OCL to provide auto-fill for deploy variables

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1337]
In order for the cloud provider UIs to provider option to choose existing configurations while deploying services.
`DeployVariable` must allow the service vendor to mention if the variable can simply use the existing data. 

- [ ] Extend `DeployVariable` to have new optional subtype - AutoFill
- [ ] AutoFill to contain fields - resourceType: DeployResourceKind Enum, isAllowCreate: boolean
- [ ] Extend DeployResourceKind to have another optional field which defines the parent resource. Eg., `SUBNET("subnet", DeployResourceKind.VPC);`
- [ ] Validation in service template register - if there is a deploy variable with AutoFill and if  the resourceType has a parent, then validate that there is another deploy variable also with autofill available for the parent resourceType. Otherwise throw exception.

**Comment by baixinsui** [comment]
I will take this.

**Comment by baixinsui** [comment]
@swaroopar The issue #1338 is based on this issue, which has been completed by @WangLiNaruto. I haven't started doing this issue yet, please assign this to @WangLiNaruto

**Comment by WangLiNaruto** [comment]
let me do it
