### ISSUE TITLE
create new API method getExistingResourcesOfType 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1338]
- [ ] Create new Controller - ExistingCloudResourcesApi
- [ ] create new service in it - getExistingResourcesOfType  - GET - /CSP/DeployResourceKind
- [ ] Based on the CSP, the requested must be routed to corresponding plugins
- [ ] Create new interface with method - `getExistingResourcesOfType` and make `OrchestratorPlugin` to extend it. 
- [ ] Implement the method for HuaweiCloud plugin and for resourceType VPC, Subnet only. (Rest to be extended in next userstories)
- [ ] Method must return a List<String>. if no resources found, return empty list.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
@swaroopar  this issue is based on the issue https://github.com/eclipse-xpanse/xpanse/issues/1337.  
I haven't started doing that issue yet, please reassign it to @WangLiNaruto

**Comment by swaroopar** [comment]
> @swaroopar this issue is based on the issue #1337. I haven't started doing that issue yet, please reassign it to @WangLiNaruto

@baixinsui sure. I have removed the assignment.
