### ISSUE TITLE
Link service template ID and the DeployedService data

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1352]
Currently there is no link between the service template ID and the deployed service. Instead we are storing the OCL data again for each deployed service which is duplicated data. 

- [ ] Remove the hidden Ocl from DeployRequestBase -> https://github.com/eclipse-xpanse/xpanse/blob/main/modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestBase.java#L93
- [ ] add a mandatory SERVICE_TEMPLATE_ID column here -> https://github.com/eclipse-xpanse/xpanse/blob/main/modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestBase.java#L93
- [ ] Extend DeployedService and DeployedServiceDetails to have the ServiceTemplateId in the response

**Comment by Alice1319** [comment]
I'll take this
