### ISSUE TITLE
 In the Myservice list, when a certain piece of data is destroyed\purged, other data cannot perform the same operation.

### ISSUE THREAD

**Issue by WangLiNaruto** [eclipse-xpanse/xpanse#1360]
In the Myservice list, when a piece of data is destroyed\purged, other data cannot perform the same operation at this time. After the data is destroyed\purged successfully, refresh the page and other data can perform the same operation.

![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/5f7c099c-3aff-446e-a38e-1e3f7d737ec6)
![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/bc105aac-f18d-480d-9abb-f7bdb316d271)

**Comment by baixinsui** [comment]
After the operation was done,  the same operation is disable for other services even I click the `refresh` button. Only refresh the page in the browser,  the operation is restored.
![chrome_JpHypcAorq](https://github.com/eclipse-xpanse/xpanse/assets/121531362/95a4a60b-ca1d-459b-9c23-52f017521f2a)
