### ISSUE TITLE
create role CSP and add listAllRegisteredServices service

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1378]
- [ ] Create a new role CSP
- [ ] add role to IAM scripts
- [ ] add role to xpanse
- [ ] create a service GetAllRegisteredServices  -> list all services similar to `listServiceTemplates`. But return without any namespace checks. 
- [ ] Enable the service for CSP and admin roles.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
I will take it.
