### ISSUE TITLE
introduce approval status to service registration

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1382]
- [ ] Introduce new status - APPROVAL_PENDING, APPROVED, REJECTED
- [ ] After the service is registered and updated - set the status to APPROVAL_PENDING
- [ ] in UserOrderableServices - return only APPROVED services
- [ ] In the deployRequest - validate that the request is only for approved service templates. 

We must ensure that the end user does not see the yet to be approved and rejected service templates anywhere.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
@WangLiNaruto This issue is based on https://github.com/eclipse-xpanse/xpanse/issues/1378, which I have completed. Let me take this.

**Comment by baixinsui** [comment]
@swaroopar Is it necessary to use state `approved` to search for the service templates based on deployment request in the method `deployService`?

**Comment by swaroopar** [comment]
@baixinsui yes you are right. We must also validate that the deployment request are only for approved service templates. Let me update the user story description with it.
