### ISSUE TITLE
implement review method for CSP user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1383]
for all services in state "APPROVAL_PENDING", the CSP can either approve or reject the service

- [ ] create new service -> reviewServiceRegistrationRequest - /review/result/${ServiceReviewResult }
- [ ] create enum -> ServiceReviewResult -> Accepted, Rejected
- [ ] if accepted -> set service status to "Approved", otherwise to "REJECTED"

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
@WangLiNaruto This issue is based on https://github.com/eclipse-xpanse/xpanse/issues/1378, which I have completed. Let me take this. @swaroopar

**Comment by baixinsui** [comment]
@swaroopar Is this new service only for those service templates in state `APPROVAL_PENDING`? Is it invalid for those templates in state `Approved` or `Rejected`?

**Comment by swaroopar** [comment]
@baixinsui yes you are right. For other states, the service must return a 400 with exception - ServiceTemplateAlreadyReviewed

**Comment by baixinsui** [comment]
@swaroopar The necessary parameter `serviceTemplateId` is lost in the new service with URI /review/result/{ServiceReviewResult}.  
I have come up with two modification plans as follows, 
1. Update the GET request URI with  /service_templates/{id}/review/result/{serviceReviewResult}
2. Use POST method with URI /service_temlates/review  and request body as follows:
{
  "id":"serviceTemplateId", (required)
  "serviceReviewResult": "value of ServiceReviewResul ",(required)
  "reviewComment": "comment"(optional, maybe we can save this comment into the DB)
}
Please help me take a look and give some suggestions.

**Comment by swaroopar** [comment]
@baixinsui good point.
We can make the service a PUT instead of post.
