### ISSUE TITLE
remove redundant use of useEffect and useState hooks in monitor components

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1396]
Remove the unnecessary use of useEffect and useState hooks in the `monitor` components.
As a rule of thumb, follow the below rules -
- [x] useEffect necessary only for creating side-effects. Refer this page for ways to avoid using useEffect - https://react.dev/learn/you-might-not-need-an-effect
- [x] useState only to store user actions.

Please refer to credentials and deployedServices component for examples.

**Comment by WangLiNaruto** [comment]
let me do it
