### ISSUE TITLE
implement auto-fill feature on UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1404]
The feature implemented in https://github.com/eclipse-xpanse/xpanse/issues/1337 userstory must be used in UI. 

- [x] As part of deployment form, if auto fill is provided for the deployment variable - then show a drop down with values loading using getResourcesOfAType service. 
- [x] If isAllowCreate is enabled - provide a check box - when selected - the dropdown must be disabled / replaced with text box
- [x] selected or provided value must be sent in the POST request to backend,

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by WangLiNaruto** [comment]
let me do it
