### ISSUE TITLE
implement approval feature in UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1413]
- [x] Add new role CSP to UI
- [x] Add new Page and route for  `Service Reviews`
- [x] Add component `Reviews`
- [x] Display list of all services in table using the [new service](https://github.com/eclipse-xpanse/xpanse/blob/main/modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceTemplateApi.java#L74)
- [x] Provide an option to view the details of the service - Could be something similar to the "update register" modal
- [x] Option in the details view to approve/reject and add comment for the service. This must be enabled only for state "APPROVAL_PENDING"

**Comment by Alice1319** [comment]
I‘ll take this
