### ISSUE TITLE
support running xpanse on one specific cloud provider

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1433]
currently xpanse is implemented to run outside any cloud provider and support deploying services on any cloud provider. We must also support running on one specific  cloud provider. This is the use case necessary to be supported for running xpanse on public cloud providers.

- [ ] add a maven profile for each csp -> when we run with specific csp profile, then the plugin of that csp is added to the final runtime jar. 
- [ ] This profile must be optional. By default, all plugins are added to the runtime jar.
- [ ] All APIs must only allow CSPs which have plugins available in the runtime. 
- [ ] Documentation to be updated in readme file.

**Comment by baixinsui** [comment]
I will take it.
