### ISSUE TITLE
Add AZ to order and migrate form

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1442]
This depends on #1439 #1441 

- [ ] If the service template contains serviceAvailabilityConfig then show a new section in the first page of new order (page where CSP, region, flavor is selected)
- [ ] For each entry in the serviceAvailabilityConfig  list, the field must be displayed using 'displayName' field and values taken from the new `getAvailabilityZones` method,
- [ ] In the submit request, value is send the availabilityZone field with map of varName and selected var value.

**Comment by WangLiNaruto** [comment]
let me do it
