### ISSUE TITLE
introduce option to modify specifications of a service

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1447]
- [ ] Create a new service - modifyServiceSpecifications - '/services/modify/{id}
- [ ] This should allow flavor change, or change of any deploy params. 
- [ ]  Add new service states -> MODIFYING, MODIFYING_FAILED, MODIFICATION_SUCCESSFUL
- [ ] Use existing stored state to trigger service modification.

Note - Please consider testing service with https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle options as well.

**Comment by Alice1319** [comment]
I'll take this.
