### ISSUE TITLE
stabilize handling of service versions

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1474]
Currently service versions are just strings. We must strictly ensure the follow the semantic versioning format. 

- [ ] use library https://github.com/semver4j/semver4j
- [ ] Validate if the provided string is a valid sementic version
- [ ] New versions for the same service name, only higher versions must be permitted.

**Comment by baixinsui** [comment]
I will take it.

**Comment by swaroopar** [comment]
Hi @baixinsui register only mainly. Update will not anyways allow to change the version and deploy I don't think version exists.

**Comment by baixinsui** [comment]
> Hi @baixinsui register only mainly. Update will not anyways allow to change the version and deploy I don't think version exists.

Ok.
