### ISSUE TITLE
make all role protection in the API layer optional

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1493]
In order to prepare the application to be deployed on different setups, it is necessary to enable/disable role protection conditionally.
Currently all our API methods are annotated with `@Secured` annotation. This must be controllable based on a config.

- [ ] use solution https://stackoverflow.com/questions/22176236/disable-enableglobalmethodsecurity-annotation
- [ ] add a new configuration property - 'enable.role.protection' with default value as `true`

**Comment by baixinsui** [comment]
I will take it.
