### ISSUE TITLE
OCL `modificationUpdate` added at wrong place for flavor

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1515]
it was requested to add `modificationUpdate` to 'flavors' in the OCL. But it is currently added to each flavor. see https://github.com/eclipse-xpanse/xpanse/issues/1448
This must be changed. 

We need `modificationUpdate` just once for all the flavors. We can create a new type called `flavors` and add modificationUpdate and List<Flavor> to it

**Comment by Alice1319** [comment]
I'll take this.
