### ISSUE TITLE
add modify option to UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1516]
Similar to destroy, add modify option to myServices page. 

- [ ] use the API developed in #1505 
- [ ] the modal should show option to change flavor and also form to update service properties
- [ ] Show warnings based on modificationUpdate value in flavors and for each property. Show respective warnings based on what the user is changing
    - Changing flavor will cause service to be restarted and data will be lost. Proceed?
    - Changing flavor will cause service to be restarted. Proceed?
    - Changing flavor will cause data to be lost. Proceed?
    - Changing flavor and service property xxxx will cause service to be restarted and data to be lost. Proceed?
    - Changing service properties xxxx and yyy will cause data to be lost. proceed?
    - ...

**Comment by Alice1319** [comment]
I‘ll take this
