### ISSUE TITLE
fix AZ implementation in UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1521]
- [ ] No skeleton shown for loading
- [ ] No error shown when loading fails
- [ ] Mandatory fields not correctly handled
- [ ] Previous selection lost when user comes back to first page.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
> let me do it

@WangLiNaruto you can ignore it. I have fixed it already.

**Comment by WangLiNaruto** [comment]
> > let me do it
> 
> @WangLiNaruto you can ignore it. I have fixed it already. I will open few other issues after this is merged. You can pick them.

@jbonofre ok,thank you
