### ISSUE TITLE
remove 'DeploymentScenario' from terraform-boot

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1529]
To keep terraform-boot as simple as possible for all clients (not just xpanse), we must get rid of any additional complexity. 

- [ ] remove DeploymentScenario field from terraform-boot.
- [ ] generate API in xpanse
- [ ] replace DeploymentScenario based logic to use different webhook for each scenario.

this userstory is just for terraform-boot, once this is successfully implemented, we can have a new userstory for tofumaker.

**Comment by WangLiNaruto** [comment]
let me do it
