### ISSUE TITLE
change flavors display type

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1536]
currently flavors are displayed as drop down. We must change it to make it as big buttons like how most of the services are displayed online. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/c3b04315-5853-4d1e-a40c-229e0e08f69c)

we need something like this

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/cdf6c584-8c29-44b1-8158-198276916806)

**Comment by Alice1319** [comment]
I‘ll take this.
