### ISSUE TITLE
add eula status to deploymentRequest and service templates

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1541]
- [ ] eula information to be returned in ISV, CSP and User service template data models. 
- [ ] add a new optional `isEulaAccepted` field to deployRequest. 
- [ ] If the service template has `eula` defined, then this field must be true. 
- [ ] if the service template has `eula` defined but the field is false, then throw new exception -> EulaNotAccepted

Depends on #1540

**Comment by WangLiNaruto** [comment]
let me do it
