### ISSUE TITLE
add eula information to UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1542]
- [ ] show eula in the register screen
- [ ] show eual content in the service catalog and update screen
- [ ] show eula with check box to accept eula in the order and migrate screen. the Eula checkbox field must be mandatory. 
- [ ] send eula status in the deploy and migrate request to backend. 

depends on #1540 and #1541

**Comment by WangLiNaruto** [comment]
let me do it
