### ISSUE TITLE
modification failure always sets service state to "not running"

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1562]
Currently if there is any failure during modification, we set the service state to "Not Running". This is not correct. 
We must set it to "Not Running" only if the deployment fails.  Otherwise we must leave the deployment state as it was before the modification process was started. 

```java
    private ServiceState getServiceState(DeployerTaskStatus state) {
        if (state == DeployerTaskStatus.DEPLOY_SUCCESS
                || state == DeployerTaskStatus.MODIFICATION_SUCCESSFUL) {
            return ServiceState.RUNNING;
        }
        return ServiceState.NOT_RUNNING;
    }
```

**Comment by baixinsui** [comment]
I will fix it.
