### ISSUE TITLE
flavor not updated after service scaling is completed

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1563]
After the service scaling request is completed, the flavor value in DB is not updated.

**Comment by baixinsui** [comment]
I will fix it.

**Comment by baixinsui** [comment]
@swaroopar If the modify failed, should we update the columns `FLAVOR` and `CUSTOMER_SERVICE_NAME` with the value in modify info? or keep these two column old values,  just only update the  filed `DEPLOY_REQUEST` which includes those info ?
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/7b642d13-6e35-4868-a901-80ff6aa2dd13)

**Comment by swaroopar** [comment]
@baixinsui yes, we must update the FLAVOR and CUSTOMER_SERVICE_NAME columns. 
Are we currently updating the "DEPLOY_REQUEST'" column with the new modify request object?

**Comment by baixinsui** [comment]
> @baixinsui yes, we must update the FLAVOR and CUSTOMER_SERVICE_NAME columns. Are we currently updating the "DEPLOY_REQUEST'" column with the new modify request object?

yes. so I think if failed, we only update the info in "DEPLOY_REQUEST", if success, update all column.
