### ISSUE TITLE
modification previous error not cleared. 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1564]
When modification deployment fails, we store the error as expected. 
But when we try the modification again and it is successful, then we are not clearing the previous error. The previous error must be deleted from the DB.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/ec096149-3ecb-4c8e-8af2-96df408470d8)

**Comment by baixinsui** [comment]
I will fix it.
