### ISSUE TITLE
dashboard to consider modification status as well

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1576]
For Successful Deployments and Failed Deployments, consider also Modification Successful and Modification Failed also. 

- [ ] Successful Deployments -> count also Modification Successful services 
- [ ] Failed Deployments -> count also Modification Failed services 
- [ ] On click, the URL must contain both service states. 
- [ ] To be changed for end user and ISV dashboards

**Comment by WangLiNaruto** [comment]
let me  do it

**Comment by WangLiNaruto** [comment]
let me do it
