### ISSUE TITLE
Extend flavor with priority information to control service downgrade

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1577]
- [ ] Add `int priority` field to `Service Flavor`
- [ ] Add `boolean isDowngradeAllowed` field to `Flavors`
- [ ] Extend scale service logic - if downgrading is not allowed, and if the new flavor's priority is lower than the current flavor's priority, then reject the request with a new exception - `ServiceFlavorDowngradeNotAllowed`

**Comment by baixinsui** [comment]
I will take it
