### ISSUE TITLE
migration modal not to show same region again

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1579]
the migration modal in the MyServices currently shows the current region of the service as well. This must be changed. 

- [ ] Rename button name to `Change Region/Cloud`
- [ ] Add first step to migration -> User selects weather he wants to change region / change cloud using a radio button 
- [ ] change `SelectDestination` component based on this. If change region -> show only current CSP and not show current region in the drop down. 
- [ ] if change CSP -> do not show current CSP.

**Comment by baixinsui** [comment]
@swaroopar  In this way, how to handle the migration of services from one region to another region of the same CSP? The modification service could not handle the case.

**Comment by swaroopar** [comment]
@baixinsui very good point. I completely missed it. Then we must only disable the same region. Let me update the user story accordingly.. Thank you.

**Comment by WangLiNaruto** [comment]
let me do it
