### ISSUE TITLE
show warnings for modify and scale options

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1586]
- [ ] Show warnings based on modificationUpdate value in flavors and for each property. Show respective warnings based on what the user is changing

Changing flavor will cause service to be restarted and data will be lost. Proceed?
Changing flavor will cause service to be restarted. Proceed?
Changing flavor will cause data to be lost. Proceed?
Changing flavor and service property xxxx will cause service to be restarted and data to be lost. Proceed?
Changing service properties xxxx and yyy will cause data to be lost. proceed?

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
@WangLiNaruto please discuss with @Alice1319 once about this user story before you start the implementation.

**Comment by WangLiNaruto** [comment]
> @WangLiNaruto please discuss with @Alice1319 once about this user story before you start the implementation.

ok

**Comment by WangLiNaruto** [comment]
> @WangLiNaruto please discuss with @Alice1319 once about this user story before you start the implementation.

@swaroopar sure

**Comment by Alice1319** [comment]
I‘ll take this.

**Comment by WangLiNaruto** [comment]
> @WangLiNaruto please discuss with @Alice1319 once about this user story before you start the implementation.

@swaroopar Hi,I discussed it with Jinping and she said she will complete this
