### ISSUE TITLE
pricing changes for end user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1592]
- [ ] In the deploy and migrate pages - show option to select between billing modes supported by the service template. 
- [ ] if only only billing mode is available, then it must be selected by default. 
- [ ] Show buttons similar to "Availability Zone" for selection of billing mode. 

depends on https://github.com/eclipse-xpanse/xpanse/issues/1590

**Comment by WangLiNaruto** [comment]
let me do it
