### ISSUE TITLE
Add new pricing API for end user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1597]
- [ ] Create new controller - PricingApiController
- [ ] add a new method - getServicePriceByFlavor -> /service/pricing/${templateId}/${region}/${flavorName}/${billingMode}
- [ ] Return the new modal `Price` as response. 
- [ ] Price to be calculated in the corresponding CSP plugin.
- [ ] As part of this user story, implement returning the fixedPrice only.

**Comment by baixinsui** [comment]
I will take it.

**Comment by Alice1319** [comment]
I‘ll fix this.
