### ISSUE TITLE
migrate openapi-typescript-codegen to openapi-ts

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1606]
openapi-typescript-codegen  has announced that it will be deprecated and there is a new project which replaces it - https://github.com/hey-api/openapi-ts

- [ ] Add openapi-ts dependency to npm and generate the client again. 
- [ ] Remove openapi-typescript-codegen dependency from package.json
- [ ] Update client generation script
- [ ] update documentation

**Comment by Alice1319** [comment]
I'll take this.
