### ISSUE TITLE
Show billing modes in ISV and CSP views.

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1610]
In the register panel, ISV catalog, update service, ISV's preview views, the available billing modes must be displayed.
When "defaultBillingMode" is provided, we must find a way to add the default tag to the default billing mode. 

We can consider using tags to show the different billing modes. 

Depends on https://github.com/eclipse-xpanse/xpanse/issues/1612

**Comment by WangLiNaruto** [comment]
let me do it
