### ISSUE TITLE
add "Retry" option when loading AZ fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1611]
Currently when AZ request fails, there is no way for the user to retry the request it. We must always go back to previous page and come again. Instead, the alert must have  a retry button to retry the request if the original request fails. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/67d9dd06-90ae-4781-9800-3d0970a6dd86)

**Comment by WangLiNaruto** [comment]
let me do it
