### ISSUE TITLE
Add default billing mode option

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1612]
In order to help the UI to decide which billing mode must be selected by default, we must add a new optional field to show the default billing mode. 

1.Extend `Billing` data model with new field `defaultBillingMode`.
2. When provided, the value must be one of the values available in the billingModes field. 
3. Add description - This is  used only for display purposes. When provided, this billingMode will be selected  in the frontends by default.

**Comment by WangLiNaruto** [comment]
let me do it
