### ISSUE TITLE
use BillingMode enum to store BillingMode state instead of state

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1620]
Currently all` BillingMode states are stored as string in the state hook. It must instead be `BillingMode`  enum. 

Please check all occurrences of BillingMode and fix this. 

Example - https://github.com/eclipse-xpanse/xpanse-ui/blob/main/src/components/content/order/create/SelectServiceForm.tsx#L118

**Comment by WangLiNaruto** [comment]
let me do it
