### ISSUE TITLE
Show modification history details in UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1632]
Using the APIs implemented in https://github.com/eclipse-xpanse/xpanse/issues/1602, we must provide an option in MyServices UI.

- [ ] Add new option in the MyServices dropdown - `history`
- [ ] When clicked, use the new API to load a table in the modal - show modification ID, previous value, new value, status, etc

**Comment by WangLiNaruto** [comment]
let me do it
