### ISSUE TITLE
add new 'deleteServiceTemplate' method

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1646]
- [ ] Existing 'unregister' method must not delete the service from DB. It must only set the status to 'Unregistered'.
- [ ] UserOrderableServices must not return the 'unregistered' services. 
- [ ] add new 'deleteServiceTemplate' method which will delete the service from DB. 
- [ ] 'deleteServiceTemplate' to check if there is any active service that is using this serviceTemplate. If yes, the delete request must be rejected with HTTP 400 - ServiceTemplateStillInUseException

**Comment by baixinsui** [comment]
I will take it.
