### ISSUE TITLE
replace generic ID fields to more specific names

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1648]
- [ ] UserOrderableServiceVo - `id` -> `serviceTemplateId` - https://github.com/eclipse-xpanse/xpanse/blob/f9754bf2013dfacdc773a60b417d7fdd6bd8a697/modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java#L38
- [ ] UserPolicy and ServicePolicy- `userPolicyId` and `servicePolicyId` respectively.  https://github.com/eclipse-xpanse/xpanse/blob/82097e293b2f9c80146c31294619f1fd9a0b5798/modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicy.java#L31
- [ ] ServiceTemplateDetailVo - serviceTemplateId - https://github.com/eclipse-xpanse/xpanse/blob/f9754bf2013dfacdc773a60b417d7fdd6bd8a697/modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java#L43
- [ ] ServiceModificationAuditDetails - serviceModificationRequestId https://github.com/eclipse-xpanse/xpanse/blob/8fb4e801b728ebb81afacb7af17683e0d0fda7a3/modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/modify/ServiceModificationAuditDetails.java#L31
- [ ] MigrateRequest - originalServiceId https://github.com/eclipse-xpanse/xpanse/blob/8475effe6e79b1ac95b4984e58dc38986fc0f547/modules/models/src/main/java/org/eclipse/xpanse/modules/models/workflow/migrate/MigrateRequest.java#L33
- [ ] DeployedService - serviceId https://github.com/eclipse-xpanse/xpanse/blob/8fb4e801b728ebb81afacb7af17683e0d0fda7a3/modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/DeployedService.java#L34

**Comment by WangLiNaruto** [comment]
let me do it
