### ISSUE TITLE
add re-regsiter and delete options to service catalog

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1655]
This userstory is to integrate the API changes implemented in #1646 

- [ ] In the service catalog view - add new buttons re-register and delete - both disabled by default.
- [ ] if service is unregistered - enable "re-register" and "delete" buttons. 
- [ ] call the new API methods on click of re-register and delete buttons. 
- [ ] Add a warning yes/no message when user clicks on both re-register and delete buttons. 
- [ ] msg for successful re-register - Service submitted for review successfully. 
- [ ] msg for successful delete - Service deleted successfully. 
- [ ] update msg for succesful unregister - Service removed from catalog successfully.

**Comment by WangLiNaruto** [comment]
let me do it
