### ISSUE TITLE
change alert msg for service registration and service updaten based on status

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1661]
we changed the approval process in https://github.com/eclipse-xpanse/xpanse/issues/1652

if the service is auto-approved, then the alert messages must be changed accordingly.

- [ ] If the service status is "Approved" in the register method - then show text as - 'Service registered and added to catalog successfully'. For update,  'Service updated in catalog successfully'. 
- [ ] for reregister, then alert message must be "service added to catalog again successfully"
- [ ] if status is approval pending, then we can keep the current status messages as it is.

**Comment by Alice1319** [comment]
I’ll take this.
