### ISSUE TITLE
no flavor selected by default in migration

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1663]
In case of migration, currently there is no flavor selected by default. This must be fixed.

- [x] if the currently flavor used by customer is available also on the new CSP, then that must selected. 
- [x] Otherwise the first flavor must be selected by default.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/358252f0-2dd3-4a08-bb4d-ea79edfc9fa5)

**Comment by Alice1319** [comment]
I'll fix this.
