### ISSUE TITLE
EULA flag works only after unchecking and checking again in migration

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1664]
In case of migration, if the user accepts the EULA and goes to next page. In case he revisits the previous page, then the EULA warning is shown even if the EULA is accepted. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/5aadbb1f-8b40-40c4-aac7-0ddaecdb3144)

**Comment by WangLiNaruto** [comment]
let me do it
