### ISSUE TITLE
update flavor view in service catalog views

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1669]
Wherever service details are displayed, the flavor component must be changed. Currently it is too big and the data is lost. 

Change this flavor display as the following

1. Show one entry for each flavor name. 
2. Flavors to be listed one below the other. 
3. on flavor mouse over, show the detail of that respective flavor. 
4. If the mouse over view is too big, then add scroll automatically. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/a5a7de1f-102d-4103-a378-c0fcc045e953)

**Comment by Alice1319** [comment]
I‘ll take this.
