### ISSUE TITLE
request retry times must be used only for http errors

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1672]
Currently the http request retry strategy is used for all purposes. But it must be used only for http errors.

In the code below, we are using the http request retry also to decide the number of times we must poll the job status. This must be separated. 

For polling the job, we must use a different configuration and in case of Huaweicloud plugin, we must set here a value as high as possible. (I assume the max allowed value is 30). 

https://github.com/eclipse-xpanse/xpanse/blob/main/plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudVmStateManager.java#L145

**Comment by swaroopar** [comment]
@baixinsui kindly check this issue.

**Comment by baixinsui** [comment]
I will fixed it.
