### ISSUE TITLE
Add 'service hosting type' column to review service table 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1684]
- [ ] We must add 'Service Hosting Type' column to the review service table. 
- [ ] The display must use the same format that is used to display the hosting type in same format that is used to display in OCL display. 
- [ ] Also the display type in MyServices and report must also be updated to have the same way/colors that we use in the OCL display. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/fe6dd535-9c4f-40bb-9e94-23dc7c310f08)

**Comment by WangLiNaruto** [comment]
let me do it
