### ISSUE TITLE
Add service catalog to CSP role

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1685]
Currently the CSP user cannot see the complete list of services available on that cloud service provider. 

- [ ] we can use the similar tree structure that is used in ISV services view
- [ ] The tree must be grouped like this -
1. by software vendor - using the namespace field in the templates. 
2. Inside the vendor - category
3. Inside category - service name
4. inside service name - versions
- [ ]  on the right side - we show everything similar to ISV view. Except remove the  the CSP tabs.

**Comment by Alice1319** [comment]
I‘ll take this.
