### ISSUE TITLE
enable 'back' button when deployment fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1686]
- [ ] Enable back button when deployment fails. 
- [ ] Consider for both deploy and migrate

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/23971e65-5262-42e0-91f1-5a156807a861)

**Comment by Alice1319** [comment]
I'll take this.

**Comment by WangLiNaruto** [comment]
let me do it
