### ISSUE TITLE
UI-Purge modification failed services always failed.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1689]
When click the option `purge` to purge a service with state `modification failed` will always get a error response. The option `purge` should be replaced with `destroy`.
![msedge_BX4lP4uNGd](https://github.com/eclipse-xpanse/xpanse/assets/121531362/2347739d-aec1-450d-a93a-482a889461b9)
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/e815f665-a321-40dd-a70f-fcfc5a748dd2)

**Comment by WangLiNaruto** [comment]
let me do it
