### ISSUE TITLE
Add unique values in list validation for OCL

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1696]
In OCL, the regions list currently allows us to provide  name multiple times. Such list entries must be checked to ensure that the list contains unique values. 
Similar to `region`, we must also check other list fields in OCL where the values must be unique - Eg., deploy variables, AZs, ServiceProviderContactDetails, etc

- [ ] Add validation - consider using using https://stackoverflow.com/questions/47293514/bean-validation-jsr-303-duplicateitemcheck-for-a-list-in-java
- [ ] Throw exception - ListElementsNotUniqueException - with message containing exact field name and which value is duplicate.
- [ ] update description of the API fields to mention that the list elements must be unique.

**Comment by baixinsui** [comment]
I will take it
