### ISSUE TITLE
review service buttons remains disabled if the service is again sent for approval

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1703]
Step 1 - CSP approves a service. 
Step 2 - ISV updates the service again. 
Step 3 - CSP has still not logged out. Just refreshed the table. 
Step 4 - The approve and reject button remains disabled. 

https://github.com/eclipse-xpanse/xpanse/assets/54129659/bd05b048-82ce-4b8d-8ae7-fee379d732ed

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by swaroopar** [comment]
@WangLiNaruto we have new issues after this fix. The approve and reject buttons are always enabled for all services.
