### ISSUE TITLE
handle multiple cloud providers based on same cloud implementation

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1709]
In order to handle multiple clouds based on same cloud implementation - Eg., Regio Cloud and Plus Server are both SCS based clouds,
Also multiple clouds can have Openstack based clouds. In fact, SCS itself is based on Openstack. 
To leads to new requirements - 
1. Plugins should be based on CSPs and not implementations
2. Duplicate code must be removed. 

- [ ] Create new package in plugins -> common and under common one more package - openstack-common
- [ ] Use openstack-common code in openstack and SCS plugins .
- [ ] update CSP enums to have new values - RegioCloud, Plus Server, Openstack-Testlab
- [ ] Remove CSP enums -> SCS, Openstack. 
- [ ] Add plugin code  for  RegioCloud, Plus Server, openstack-testlab (rename openstack)
- [ ] For each of the openstack and SCS based clouds, we need a mandatory required property for the keystone URL 
   https://github.com/swaroopar/osc/blob/0f53ec967c5e24189748045520a168839a3ff945/plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java#L96

- [ ] This required property must be unique. No plugin must have a mandatory field `OS_AUTH_URL`.  Because this is a common name and when an env var is set with this name, then all plugins (even Huawei Cloud) use this var and then causes unexpected issues. 
 example - openstack_testlab_url, regiocloud_url, etc 
This must be mapped to OS_AUTH_URL in the terraform deployer. 
- [ ] add service Id to getExistingResourceNamesWithKind method as well.

**Comment by swaroopar** [comment]
@baixinsui please consider this

**Comment by baixinsui** [comment]
I will take it.
