### ISSUE TITLE
Add service configuration parameters to OCL

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1718]
It is necessary to support configuration parameters of a service that can be updated. 

- [ ] Similar to DeployVariable - Create ServiceConfigurationParameter type with fields - same as DeployVariable. 
- [ ] add extra parameter - InitialValue - mandatory field
- [ ] Add `configurationParameters`  field to OCL with type `List<ServiceConfigurationParameter`

**Comment by WangLiNaruto** [comment]
let me do it
