### ISSUE TITLE
add audit table entry for redeployment requests

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1723]
As part of the redeployment request, the old deployment details must be cleared from the SERVICE_DEPLOY  table and moved to the audit table. 
https://github.com/swaroopar/osc/blob/38bef5dbc922cbc991d4b387ae9b2cb43f3253a8/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java#L276

- [ ] rename the table 'SERVICE_MODIFICATION_AUDIT' to 'SERVICE_MANAGEMENT_AUDIT'
- [ ] add a new column 'operation_type' with one value in the OperationTypeEnum('create','modify','migrate','redeploy','delete','purge'...)
- [ ] Redeployment must clear the error details from SERVICE_DEPLOY and move it to SERVICE_MANAGEMENT_AUDIT table.

**Comment by baixinsui** [comment]
I will take it.

**Comment by swaroopar** [comment]
1. Introduce a new "Order ID" for each change user requests. 
2. Return this as ID in the response for each of the modification request - 'create','modify','migrate','redeploy','delete','purge'...
3. Order ID is nothing but the ID column in the SERVICE_MODIFICATION_AUDIT (new name SERVICE_MANAGEMENT_AUDIT)
4. Recently added a new service status API https://github.com/eclipse-xpanse/xpanse/pull/1738 ->
       - change this to order status instead of service status everywhere. 
       - Extend the response to include the error message of the order. 

For UI
1. Remove polling the service details. Instead poll the order status using the new API. This will solve our current problem since we will have new ID for retry request. So the polling query is always newly created for the new order ID. 
2. Get the service details only to get the end point details of the service.
