### ISSUE TITLE
refactor all occurrences of findAll() JPA repository method which is an anti pattern

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1724]
Currently there are some occurecues of JPA's `findAll()` method which is an anti-pattern since it loads the full table from DB into the java memory. 

More details - https://vladmihalcea.com/spring-data-findall-anti-pattern/

Preferred solution -

- [ ] As mentioned the above blog, create a custom repository with only the methods are necessary for xpanse. 
- [ ] Create an architecture test to ensure that no repository is created with inbuilt repository methods.  (Check existing architecture tests)

**Comment by baixinsui** [comment]
I will take it.
