### ISSUE TITLE
UI-Unable to view details of services deployed failed in the page

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1736]
In the page `MyServices`, the option `details` is disabled when the service deployed failed.
![chrome_akyZpnvovX](https://github.com/eclipse-xpanse/xpanse/assets/121531362/14d517f7-c9b4-447c-a5c0-bc5322ae67f4)

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
Fixed by the PR https://github.com/eclipse-xpanse/xpanse/pull/1738
