### ISSUE TITLE
Next button not handled correctly

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1749]
Currently the 'next' button in the new service creation is not handled correctly. It is inconsistent. 

1. 'next'  button must be disabled until prices and availability zone is loaded. 
2. if Availability zone is optional in the template -> then the 'next' button can be enabled even if loading availability services fail. 
3. If prices loading fails -> then the 'next' button must be disabled. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/15a33ef4-6da0-453a-ad80-2f6d6cfac785)

**Comment by WangLiNaruto** [comment]
let me do it
