### ISSUE TITLE
issue with changing service hosting type when flavors are different

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1765]
1. Create a same service with different hosting types and also different flavor names in these two services. 
2. Changing the service hosting type after flavors are loaded is crashing the UI. 

https://github.com/eclipse-xpanse/xpanse/assets/54129659/e803d357-b463-4d05-a71b-cb225a5fa1b2

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
I’ll take this.
