### ISSUE TITLE
Update error alert when AZ loading fails and AZ is not mandatory field

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1767]
When an AZ field is not mandatory and if the loading of AZ fails. 

1. Show alert type in orange instead of red. 
2. add hint that to alert -> This Availability Zone is not a mandatory field. You can proceed without this, and the service will be deployed on one of the availability zones of the regions by default.

**Comment by WangLiNaruto** [comment]
let me do it
