### ISSUE TITLE
store initial configuration of the service during service deployment

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1774]
As part of service configuration update, we must start with storing initial service configuration properties during the service deployment. 

- [ ] Add new table SERVICE_CONFIGURATION with foreign Key as the ID of the DEPLOY_SERVICE table. and CONFIGURATION column 
- [ ] CONFIGURATION column stored configuration as JSON. 
- [ ] Add created and updated time columns 
- [ ] Extract initial configuration as below - 
    1. JSON Key is `name` of ServiceConfigurationParameter
    2. Value is the `initialValue` of ServiceConfigurationParameter
    3. If the same `name` is present in the flavor properties, then that value from the deployed flavor must be used as the initial value. 
- [ ] Use  kafka service properties from bitnami kafka docker image and update the service template
https://github.com/bitnami/containers/tree/main/bitnami/kafka#111-debian-9-r205-220-debian-9-r40-111-ol-7-r286-and-220-ol-7-r53
To start with, we can only provide the following configuration parameters in the template - KAFKA_CFG_MESSAGE_MAX_BYTES, KAFKA_CFG_LOG_DIRS, KAFKA_CFG_NUM_IO_THREADS, KAFKA_LOG_FLUSH_INTERVAL_MESSAGES, KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR

**Comment by WangLiNaruto** [comment]
let me do it
