### ISSUE TITLE
ServiceConfigurationParameter - Extend the parameter with resource information

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1788]
For each ServiceConfigurationParameter, it is necessary to add the resource information to which the configuration parameter belongs to.  Using this, we can decide on which VM we must run the configuration change 

- [ ] add a new string field called `managedBy` to `ServiceConfigurationParameter` class
- [ ] Add validation to check if the resource name provided in the `managedBy` field is correct. This must be validated as part of the service registration and update. 
- [ ] Add a new method to `OrchestratorPlugin` interface - GetResourcesInServiceDeployment.
- [ ] Return  map of resource name and resource type. 
 We can consider using [hcl4j](https://github.com/bertramdev/hcl4j) to parse the HCL file. 
- [ ] Use this method to validate the service configuration parameters.

for the example below, resource name is "kafka-broker" and type is "huaweicloud_compute_instance" and resource name is 
```hcl
resource "huaweicloud_compute_instance" "kafka-broker" {}
```

**Comment by WangLiNaruto** [comment]
let me do it
