### ISSUE TITLE
active deployment services must not be shown for CSP user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1789]
Active deployments field is shown currently also for CSP user. This is fine but the "view services" link is not needed. 
It currently takes to a page which is not valid for CSP user. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/4c670864-cce3-4814-baae-480387254a6f)

**Comment by WangLiNaruto** [comment]
let me do it
