### ISSUE TITLE
fix styles for order and migrate components

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1790]
- [ ] All items in the page have rounded corners. Only the CSP image does not have rounded corner. So even this must be changed to have rounded corners. 
- [ ] Place all values of form fields to start from same place. The placement must be changed. At the moment this is not uniform. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/598f7b13-7659-4218-9398-409d62cb0d8f)

**Comment by Alice1319** [comment]
I‘ll take this.
