### ISSUE TITLE
display issues with AZ in new order

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1821]
- [ ] Error alerts are overlapping. We must add border. 
- [ ] When loading , the skeleton should be in same level as the form field name. 
- [ ] In case of optional field, the alert does not show the error returned from backend. 

![image](https://github.com/user-attachments/assets/af820b99-dc71-4920-93b7-9427eb257b9d)

![image](https://github.com/user-attachments/assets/5a0a0709-a58c-4e9d-9401-f174f3c162ef)

![image](https://github.com/user-attachments/assets/965f3c01-7448-4723-8ddd-079d8d0c171c)

**Comment by WangLiNaruto** [comment]
let me do it
