### ISSUE TITLE
fix spacing of different blocks in register panel

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1836]
We must keep both the blocks in same position. 

Basic information table must be moved to the same level of the first flavor. 

Note - the spacing seem to be fine, if there are two flavors only. but misplaced when there are more than 2 . 

![image](https://github.com/user-attachments/assets/4097f65a-25f9-41b5-8ea6-97d0581fc1ad)

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by WangLiNaruto** [comment]
let me do it
