### ISSUE TITLE
order status set to failed before rollback is completed

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1846]
Currently we are setting the status of order to failed as soon as the deployment fails. The frontend then does not know that the order is actually being currently rolled back. So if the rollback fails, the frontend does not has this information. It instead assumes that the order process is completed since the order status is failed already. 

- [ ] Do not set the status of the order to FAILED immediately
- [ ] Wait for rollback to be completed. 
- [ ] After that set FAILED.

**Comment by baixinsui** [comment]
This problem has been fixed by https://github.com/eclipse-xpanse/xpanse/pull/1835/commits/05c08bbcf4eacfc4f3713a131b477ee113923df9#diff-1bb984b9537e2e0f70b090596cfff3583e1379b451f487fc33eb8ebe0f8191ac

**Comment by swaroopar** [comment]
@baixinsui I think the problem is mainly due to async rollback process and we do not wait for it. 

Rollback is triggered here - https://github.com/swaroopar/osc/blob/475ae8102e9a68231535115b2d4aa94db7c783ae/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/callbacks/TerraformDeploymentResultCallbackManager.java#L75

But the control does not wait here. It immediately goes here to - https://github.com/swaroopar/osc/blob/475ae8102e9a68231535115b2d4aa94db7c783ae/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/callbacks/TerraformDeploymentResultCallbackManager.java#L84

We need to handle this in such a way that the order status is updated only after rollback is completed.

**Comment by baixinsui** [comment]
@swaroopar Yes. Now the order status is updated only after rollback is completed. https://github.com/eclipse-xpanse/xpanse/blob/main/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java. When the deploy failed and then call back this method, only error information is recorded without setting the status and end time; https://github.com/eclipse-xpanse/xpanse/blob/main/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java#L214-L219. Only when the rollback task call back this method, set the order status to 'failed' and set the complete time.https://github.com/eclipse-xpanse/xpanse/blob/main/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java#L206-L209.
