### ISSUE TITLE
avoid retries for 401 and 403 HTTP errors in cloud API requests

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1848]
Currently the plugins calling the cloud APIs are retrying all failures. But the permanent errors must not be retried. 

- [ ] Disable retries for 401 and 403 errors
- [ ] Log request and responses sent and received from Huaweicloud APIs by the SDK.

**Comment by baixinsui** [comment]
I will take it

**Comment by baixinsui** [comment]
@swaroopar The task about log already done in https://github.com/eclipse-xpanse/xpanse/issues/1673
Just change the default value `false` to `true` of item `huaweicloud.sdk.enable.http.debug.logs`
![idea64_PQWtLwubu0](https://github.com/user-attachments/assets/47db508b-ef20-48a9-8e99-d495837b39dc)

**Comment by swaroopar** [comment]
@baixinsui ah ok. That's good. Then we implement only the first requirement.
