### ISSUE TITLE
add new optional field "site" to credentials configuration

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1849]
While testing different environments, we found out that there are some CSPs who run completely separated sites with completely separated management layer (separate IAM, console, etc)

- [ ] AbstractCredentialInfo - extend to have an mandatory string field `site`. Description of the field - site to which the the credentials belong to. 
- [ ]  Add `site` to credential cache key. 
- [ ] Extend all credential 'get' methods to use 'site' also in the query key. 
- [ ] Extend all methods in class `HuaweiCloudCredentials` to set IamEndpoint based on region. It must be mandatory to set region. 
- [ ]  Additionally set credential based on the site to which the region belongs to. 
- [ ] In case of billing API -> if no credentials are available for the requested site, then use the API which works without credential. 
`.withIamEndpoint(IamRegion.valueOf(region).getEndpoints().getFirst());`

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
I will take it
