### ISSUE TITLE
Adapt changeServiceConfiguration API

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1867]
- [x] Split the config request into multiple ones based on the config manager which is responsible for the configuration paramters. 
- [x] All config requests must have same order ID. 
- [x] If the service component has multiple nodes and if runOnEach is true, then add multiple entries for each resource. 
- [x] Use the getComputeResourceInventoryOfService to get the names of the resources. 
- [x] Store all requests to DB. 

Depends on https://github.com/eclipse-xpanse/xpanse/issues/1868

**Comment by WangLiNaruto** [comment]
let me do it
