### ISSUE TITLE
Change Table SERVICE_CONFIGURATION_UPDATE_REQUEST

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1868]
- [x] add SERVICE_ID - make it a foreign key of DEPLOY_SERVICE table. 
- [x] ORDER_ID should be foreign key of order table. 
- [x] Add RESOURCE_NAME column. 
- [x] Add CONFIG_MANAGER column. 
- [x] RESULT_MESSAGE column

**Comment by WangLiNaruto** [comment]
let me do it
