### ISSUE TITLE
allow OCL to support 'site' for regions. 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1890]
While testing different environments, we found out that there are some CSPs who run completely separated sites with completely separated management layer (separate IAM, console, etc). Hence it is necessary to support regions on different 'sites'. 

- [ ] Extend the Region object in OCL to have a new mandatory 'site' field - should be string. 
- [ ] Add a new method to OrchestratorPlugin interface - getSites - return String[]. 
- [ ] If the CSP does not have multiple sites, then the plugin can return ['default']
- [ ] Region validation in service registration must be extended to allow same region name for multiple sites.

**Comment by baixinsui** [comment]
I will take it.
