### ISSUE TITLE
add distributed locking mechanism for requests from agents

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1913]
- [ ] if `runOnlyOnce` is set to `true` then the `resourceName` column must be set to blank.  This will be flexible that any resource in the deployment can fetch the pending request. 
- [ ] When getPendingConfigurationChangeRequest is received, return the pending request with either resource_name specific for the resource_name in the request URI or with the resource_name  is empty. If the resource_name is empty, check if the resource_name in the request belongs to the same `config_manager` group in the service inventory. 
- [ ] To enable distributed locking - the read from DB must be executed using JPA `LockModeType.PESSIMISTIC_WRITE`. And the update of the status to IN-PROGRESS. Both must be wrapped under one `@transactional`
- [ ] Set `javax.persistence.lock.timeout` to 2seconds for this specific transaction and return when LockTimeoutException` occurs then return HTTP 204. 
- [ ] Test that when multiple requests are received, only one gets processed and other one waits until the distributed lock is released. 
- [ ] In the pollingApi, if the config update order with resource_name empty is returned to an agent, then update that agent's resource_name in the entry. So that we then know that which resource has actually got the request and is processing it. 

depends on #1869

**Comment by WangLiNaruto** [comment]
let me do it
