### ISSUE TITLE
UI-Shown Available Regions error

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1925]
When the service template with only one region, the shown Available Regions is empty, this must be fixed.
![chrome_qGuVRygiX4](https://github.com/user-attachments/assets/94d1390b-a090-4bf9-8226-e07384430d58)

**Comment by baixinsui** [comment]
@Alice1319  This problem in the code in https://github.com/eclipse-xpanse/xpanse-ui/pull/1128, please check it

**Comment by Alice1319** [comment]
I'll test this
