### ISSUE TITLE
End User Scale Service error

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1936]
When the user has no role(default granted user)  select options scale or modify parameters of a deployed service, the UI client will call the API `/xpanse/service_templates/{serviceTemplateId}` which need users have role `ISV` and return 403 error, this cause the page error.
Modify parameters of the service error:
![chrome_Qxvm9Me4cj](https://github.com/user-attachments/assets/e36f36b2-8518-4650-847d-9e040b09365d)
Scale the service error:
![image](https://github.com/user-attachments/assets/0108fb48-a615-4c8b-83da-c3b3d7efeca1)

This error must be fixed. There are two solutions as below:
1.  The UI Client change to call the API `/xpanse/catalog/services/{serviceTemplateId}` which is for the end users in all pages for the end users.
2.  In the back-end, add role `User` into the needed roles of the API `/xpanse/service_templates/{serviceTemplateId}`.

**Comment by swaroopar** [comment]
@baixinsui we must use the API which is specifically for end user. This must be fixed on the UI.

**Comment by baixinsui** [comment]
@swaroopar I tried to replace the API in the UI client but there are other errors. I could not find out the caused. Can you fix it in the UI Client or assign it to other partners.

**Comment by swaroopar** [comment]
@Alice1319 could you please check this bug? We are using a wrong API to fetch service template details.

**Comment by Alice1319** [comment]
Sure,I'll check this
