### ISSUE TITLE
Deploy compute of Openstack error with latest terraform

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#1938]
Run the scripts with terraform v1.6.1+, will cause bellow errors:
![image](https://github.com/user-attachments/assets/156df83a-4015-4dd8-b56e-47d25ae978ef)

![image](https://github.com/user-attachments/assets/0dea55d3-29fc-4eec-8f77-cb5b7ebe8d07)

But when run with terraform v1.6.1, there are no errors.

**Comment by baixinsui** [comment]
I will fix it.

**Comment by swaroopar** [comment]
Will be fixed with other userstories.
