### ISSUE TITLE
extend OCL with deployer tool version

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1940]
In order to ensure the deployer script is executed with the correct version of the tool for which the deployer scripts were developed, it is necessary to also store the version of the deployer tool in OCL. 

- [ ] Add new type DeployerTool with two fields -> DeployerKind and version. 
- [ ] OCL to have DeployerTool field and remove DeployerKind
- [ ] The version must support specific version, greater than or equal to and lesser than or equal to. Any other format must be rejected.
- [ ] Update all samples.

The version should be passed on to deployer later as part of other user stories.

**Comment by baixinsui** [comment]
I will take it
