### ISSUE TITLE
extend terraform and opentofu local deployers to support multiple versions

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1941]
Similar to #1939 , the same logic must be implemented in local deployer tools as well. 

- [ ]  all terraform commands must be extended with the version name. example terraform-1.16 apply
- [ ]  if no binary with this name is not found, assume the terraform is not installed, and try to install it. Note -> if it is running in a docker container, then it is installed within the docker container.
- [ ]  Installation path, download base URL must be configurable.
- [ ]  Dynamically build download the file name based on the version, OS name and the processor architecture.
- [ ]  If the installation fails, then return an exception with all information in the async response.

Depends on #1939 and better to be implemented by same developer.

**Comment by baixinsui** [comment]
I will take it
