### ISSUE TITLE
extend tofu-maker to support multiple versions of terraform

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1942]
- [x] Extend all request body with 'opentofu_version' field. 
- [x] The version can be a specific version, greater than or equal to, lesser than equal to. Based on that use whatever terraform installation is available that fits the requirement. 
- [x] all terraform commands must be extended with the version name. example `opentofu-1.7 apply` 
- [x] if no binary with this name is not found, assume the terraform is not installed, and try to install it. Note -> if it is running in a docker container, then it is installed within the docker container. 
- [x] Installation path, download base URL must be configurable. 
- [x] Dynamically build download the file name based on the version, OS name and the processor architecture. 
- [x] If the installation fails, then return an exception with all information in the webhook response. 

Depends on #1939 . To be implemented after this is done.

**Comment by baixinsui** [comment]
I will take it

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
@swaroopar Please reassign this to me.

**Comment by swaroopar** [comment]
Implemented and merged.
