### ISSUE TITLE
Move deployment information from basic information block

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1944]
- [x] create new Deployment information block below 'Basic Information' block. 
- [x] Use same `Descriptions` antd component to show all deployment information
- [x] Deployerkind - replace text with logos of respective deloyment tools. 
- [x] Add deployer version field. 
- [x] Add service availability config field. Again with pop-over 
- [x] Add deployment script field - It must either show the deployer script or scriptsRepo information. 
- [x] Move deploy variables to a separate own table.. similar to service polices. 
- [x] Changes must reflect in register, service catalog, ISV review, service update components. 

only the 4th point is dependent on #1940 user story. Rest can be already implemented.

**Comment by Alice1319** [comment]
I'll take this.

**Comment by swaroopar** [comment]
@Alice1319 The API is updated already by @baixinsui so please use the latest interface for the entire user story.
