### ISSUE TITLE
update terraform-boot and tofu-maker Dockerfiles to support multiple version of tool

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1945]
- [ ] As part of the release build of terraform-boot and tofu-maker, the user can provide the list of versions of the tools that can be installed. 
- [ ] If not provided, a default assumed list of most widely versions of the tool must be used and installed. 
- [ ] Create executables with `name-version` format.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by baixinsui** [comment]
I will take it

**Comment by baixinsui** [comment]
@swaroopar Please reassign this to me.
