### ISSUE TITLE
store complete service configuration change request information

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1965]
Currently when the `changeServiceConfiguration` is received, we are directly splitting the requests for each configManger and storing it. So there is no table which holds the full request from the customer and overall status of the request. 

~~- [ ] Create new table SERVICE_CONFIGURATION_CHANGE -> ORDERID (PK), with SERVICEID (FK), config paramters from request, status - (ServiceConfigurationStatus), created time and updated time.~~
- [ ] Extend SERVICE_ORDER table with new column NEW_CONFIG_REQUEST.
- [ ] Rename the SERVICE_CONFIGURATION_UPDATE_REQUEST table to SERVICE_CONFIGURATION_CHANGE_DETAILS
- [ ]  Whenever any polling request comes and a request is picked up, then the status in SERVICE_ORDER must also be updated. 
- [ ] Whenever there is updateConfigurationChangeResult, we must check if all requests in 'SERVICE_CONFIGURATION_CHANGE_DETAILS' is set to SUCCESSFUL then we update SERVICE_ORDER state also to SUCCESSFUL.  and if any of them is in ERROR, then we set this to ERROR as well. 
- [ ] Extend the getAllServiceConfigurationUpdateRequests service to also include the full request properties and also the status of the change order

**Comment by WangLiNaruto** [comment]
let me do it
