### ISSUE TITLE
update SERVICE_CONFIGURATION table after completion of config update request

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1966]
SERVICE_CONFIGURATION table holds the current active configuration of the service. Whenever the service config update request is completed, we must updated the configuration information on this table. 

- [ ] When the status of the order in SERVICE_CONFIGURATION_CHANGE  is set to SUCCESSFUL, then the new configuration must be copied to SERVICE_CONFIGURATION table.

**Comment by WangLiNaruto** [comment]
let me do it
