### ISSUE TITLE
getPendingConfigurationChangeRequest returns HTTP 204 with wrong response body

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1968]
When getPendingConfigurationChangeRequest returns 204, it must not return any response body. 

20240925 12:22:35.713 [http-nio-8080-exec-6] INFO  o.e.x.m.logging.CustomHttpLogWriter [e09c3a0b-112d-4d06-ba41-58caf16a0c7c] [] []- Response: 204 No Content Duration: 3ms  {"orderId":null,"configParameters":null,"ansibleScriptConfig":null,"ansibleInventory":null}

**Comment by WangLiNaruto** [comment]
let me do it
