### ISSUE TITLE
add config parameters list to service catalog display

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1972]
- [ ] Display service parameter details in table format in all views - register panel, catalog, update, CSP catalog. 
- [ ] This is something similar to https://github.com/eclipse-xpanse/xpanse/issues/1944 for deploy variables. 

Depends on https://github.com/eclipse-xpanse/xpanse/issues/2009

**Comment by WangLiNaruto** [comment]
let me do it
