### ISSUE TITLE
add service configuration option to myservices

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1975]
- [ ] add new 'service configuration' option to 'More' drop down. 
- [ ] On click, a modal must open which has a left Menu. Consider using the antd's `Menu` component. 
- [ ] Add first menu item - `Current Config`
- [ ] Use the API method implemented in https://github.com/eclipse-xpanse/xpanse/issues/1967 to show the current configuration as a form. 
- [ ] For each config field, show description of the form field using the service template. 

Note - Depends on https://github.com/eclipse-xpanse/xpanse/issues/1967
More options to the menu will be added with other userstories.

**Comment by WangLiNaruto** [comment]
let me do it
