### ISSUE TITLE
SERVICE_CONFIGURATION_UPDATE_REQUEST table shows only one FK index

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1976]
The serviceOrderEntity is linked as a FK in the table but the table definition on the database shows only one FK on the deploy_service table. 

https://github.com/swaroopar/osc/blob/f1dd0d88c90c05ce0ff9fa8328424c23fb806016/modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceConfigurationUpdateRequest.java#L57

![image](https://github.com/user-attachments/assets/55601c7c-59f3-42bf-8103-bd1f63219c58)

**Comment by WangLiNaruto** [comment]
let me do it
