### ISSUE TITLE
fix updateConfigurationChangeResult return code and store task information

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1981]
- [x] Return HTTP 204 no content for updateConfigurationChangeResult instead of HTTP 200
- [x] Extend the SERVICE_CONFIGURATION_UPDATE_REQUEST table with TASK_RESULT column and store the `tasks` information from the ServiceConfigurationChangeResult object.

**Comment by WangLiNaruto** [comment]
let me do it
