### ISSUE TITLE
use all files in GIT repo for finding compute resources

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2020]
Currently only the firs *.tf file is used to calculate the compute resources. This must be changed. The repo can have any number of files and we must extract the information for all terraform files.

https://github.com/swaroopar/osc/blob/f482bef4433ac5286a9fe954f9bc2ae1f766a77f/modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceConfigurationParameterValidator.java#L88

**Comment by WangLiNaruto** [comment]
let me do it
