### ISSUE TITLE
Merge SERVICE_STATE_MANAGEMENT_TASK to SERVICE_ORDER

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2026]
In order to consolidate DB structure, we will make SERVICE_ORDER table as the master table to hold all changes requested on the service. 

- [ ] Remove SERVICE_STATE_MANAGEMENT_TASK table completely. 
- [ ] Record all changes only to SERVICE_ORDER. 
- [ ] Extend ServiceOrderType enum with SERVICE_START, SERVICE_STOP and SERVICE_RESTART
- [ ] Update ServiceStateManageApi to use SERVICE_ORDER table for all changes. 
- [ ] Delete services deleteManagementTaskByTaskId, deleteManagementTasksByServiceId, listServiceStateManagementTasks, getManagementTaskDetailsByTaskId
- [ ] For start, restart, stop - return ServiceOrder object. Ensure exceptions also contain the serviceId and OrderId
- [ ] Remove latestRunningManagementTask and latestModificationAudit fields in DEPLOY_SERVICE

**Comment by Alice1319** [comment]
I‘ll take this.
