### ISSUE TITLE
switch status polling of service state requests

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2028]
Currently the status polling of service state requests are still using the old methods. It must be changed similar to deploy and destroy status polling. 

- [ ] Use getLatestServiceOrderStatus for polling
- [ ] Use all details from getLatestServiceOrderStatus only. 
- [ ] Only if necessary use the getServiceDetailsById to fetch any details after  the order is completed. 

Depends on https://github.com/eclipse-xpanse/xpanse/issues/2026

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
I'll take this.
