### ISSUE TITLE
consolidate and track all changes into service_order

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2031]
**common changes**
- [x] Use ORDER_ID for all requests to deployer. Use ORDER_ID to correlate the callbacks instead of SERVICE_IDs. 
- [x] Have just one webhook API for callback from deployer. Then based on the order_id we can know which service and type of order it is.
- [x] SERVICE_ORDER changes - Add columns PARENT_ORDER_ID, WORKFLOW_ID, ORIGINAL_SERVICE_ID (used by MIGRATE orders)
- [x] Check if we can get rid of 'DeploymentScenario' and use only the ServiceOrderType enum instead. This is necessary to avoid duplicate enums. 

**changes to deployment**
- [x] change deployer requests to use ORDER_ID - update for local and remote deployers. 
- [x] Create ROLLBACK as new ORDER_TYPE.
- [x] In case of deployment error and if rollback is required - create a new rollback order. set parent_order_id as the order which failed. Process rollback response as before. 
- [x] Test changes so that nothing breaks. 

**changes to destroy**
- [x] change destroy request to use ORDER_IDs. 
- [x] Use common callback methods to process responses from deployer.

**changes to retry**
- [x] rename all methods and enums to use the word RETRY instead of REDEPLOY
- [x] Rest remains as before. 

**changes to purge**
- [x] no changes expected. Should work with above changes from DESTROY. 

**changes to modify**
- [x] no changes expected. Should work with the above changes from DEPLOY. 

**changes to recreate**
- [ ] no changes expected. Should work with the above changes from DEPLOY and DESTROY.
- [ ] Other changes planned already in https://github.com/eclipse-xpanse/xpanse/issues/2029 

**changes to migration workflow**
- [ ] Remove SERVICE_MIGRATE table
- [ ]  Extend ServiceOrderType with MIGRATE
- [ ] When MigrateRequest is received - create the workflow and add the service_order with type MIGRATE and WORKFLOW_ID with the activiti process instance ID. 
- [ ] Deploy and destroy to directly call the 'deploy' and 'destroy' methods on the ServiceDeployApi controller class. 
- [ ] Extend the deploy and destroy methods with parameters - parentOrderId and workflowId. These parameters must be hidden using `@Parameter(hidden = true)`. This means the parameters are not visible in the REST API. but will be used only by our internal calls. 
- [ ] Use the parentOrderId and workflowId to generate SERVICE_ORDER entry with extra details but does the same steps as regular deploy and destroy. 
- [ ] Take UserId from the parentOrderId
- [ ] Delete all extra methods written specially to handle migration requests. 
sequence diagram - https://www.mermaidchart.com/raw/a964c8cb-e99e-4040-bcdc-656593c43a31?theme=light&version=v0.1&format=svg

**changeServiceLockConfig**
- [ ] Return ServiceOrder
- [ ] Store request to SERVICE_ORDER with type LOCK_CHANGE

**service config change**
- [x] change ORDER_TYPE to CONFIG_CHANGE

**Comment by swaroopar** [comment]
@baixinsui Kindly have a look into this.

**Comment by baixinsui** [comment]
I will take it.
