### ISSUE TITLE
change DEPLOY_* table structure

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2032]
- [ ] Rename tables - 
             - DEPLOY_RESOURCE -> SERVICE_RESOURCE
             - DEPLOY_RESOURCE_PROPERTY -> SERVICE_RESOURCE_PROPERTY
             - DEPLOY_SERVICE -> SERVICE_DEPLOYMENT
             - DEPLOY_SERVICE_PROPERTY  -> SERVICE_DEPLOYMENT_OUTPUT
             - DEPLOY_RESULT_PROPERTY  -> SERVICE_DEPLOYMENT_GENERATED_FILES

- [ ] All tables which have SERVICE_ID must use foreign key on SERVICE_DEPLOYMENT table.   => I see the foreign key is automatically added when the 'CollectionTable' annotation is used. Please reconfirm this. 
- [ ] DEPLOY_RESOURCE_PROPERTY must have FK on ID of DEPLOY_RESOURCE table.

**Comment by WangLiNaruto** [comment]
let me do it
