### ISSUE TITLE
Having issues when compile and build mirror image

### ISSUE THREAD

**Issue by Houzonglaile** [eclipse-xpanse/xpanse#2048]
We are having problems when we try to compile and build mirror image, 
COPY --chown=${XPANSE_USER}:${XPANSE_USER} runtime/target/xpanse-runtime-*.jar xpanse-runtime.jar
Error message: unable to convert uid/gid chown string to host mapping: can't find uid for user ${XPANSE_USER}: no such user: ${XPANSE_USER}
![image](https://github.com/user-attachments/assets/8bfa4cdc-6599-4103-8d6a-4a591bd2b92d)

After we delete the --chown=${XPANSE_USER}:${XPANSE_USER}
And use
`COPY  runtime/target/xpanse-runtime-*.jar xpanse-runtime.jar` 
It worked, but we are not sure what influence this will make. 
But in the futurer when we try to run the application, the application can not be started. 
![image](https://github.com/user-attachments/assets/9cd51038-f1f5-4452-96bb-e6efbd440bdb)

**Comment by Houzonglaile** [comment]
We have changed ${XPANSE_USER} to 2000 which were using in the code and it worked, but it still have the same issue in the second pic that only showing starting XpanseApplication but no Started XpanseApplication.
And we can't access the website either.
![image](https://github.com/user-attachments/assets/b0202fa4-ea88-42fb-9c0f-c81774f40712)

**Comment by swaroopar** [comment]
@Houzonglaile We are using the same docker image in our test beds and it works without any issues. 
Is the port 8080 opened in the docker container?

By the way, may i know from which team you are from?

**Comment by Houzonglaile** [comment]
@swaroopar, Yes, port 8080 is opened in the docker container. I am working for Huawei.

**Comment by swaroopar** [comment]
@Houzonglaile please open discussions and also ping us on matrix channel or Welink for further discussions.
