### ISSUE TITLE
Add URL support for service's logo

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#205]
As [icon](https://github.com/eclipse-xpanse/xpanse#:~:text=icon%3A%20%7C,kSfDe3JweW53njxeGfXkaz28VeYd86%2Baf/H8a7hgJKaebILaFzakLfxyfQLTxVB6K1K9KQAAAABJRU5ErkJggg%3D%3D) with base64 in OCL is not clear enough and takes too much space. Adding URL support may be a good way.
1. try to download the icon when registering and encode the downloaded one with base64?
2. If the URL is unavailable, the icon will fall back to a default one.

**Comment by wanglin100** [comment]
let me do it
