### ISSUE TITLE
add service configuration manage details to service catalog display

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2051]
- [ ] Display 'ServiceConfigurationManage' part of the OCL under a new block - `Service Configuration Management` - for type use logo and version as normal text. Do it similar to `Deployment Information` 
- [ ] The configManageScripts must be shown  in a separate table 'Configuration Scripts'
- [ ] See if we can show 'Configuration Scripts' and 'Configuration Parameters' as child blocks for 'Service Configuration Management'. We must discuss this during the implementation to see how this looks.

**Comment by WangLiNaruto** [comment]
let me do it
