### ISSUE TITLE
these env permeters issue?

### ISSUE THREAD

**Issue by bestshenzhen** [eclipse-xpanse/xpanse#2053]
$ cd runtime/target
$ java -jar runtime/target/xpanse-runtime-1.0.8-SNAPSHOT.jar \
--spring.profiles.active=oauth,zitadel,terraform-boot,tofu-maker
--authorization-api-client-id=${client-id} \
--authorization-api-client-secret=${client-secret} \
--authorization-swagger-ui-client-id=${swagger-ui-cleint-id}

---------------------------------------
these env permeters , where find?

**Comment by swaroopar** [comment]
@bestshenzhen please open discussion for these topics instead of issues.
