### ISSUE TITLE
change migration workflow to use order_id

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2057]
**changes to migration workflow**
- [ ] Remove SERVICE_MIGRATE table
- [ ]  Extend ServiceOrderType with MIGRATE
- [ ] When MigrateRequest is received - create the workflow and add the service_order with type MIGRATE and WORKFLOW_ID with the activiti process instance ID. 
- [ ] Deploy and destroy to directly call the 'deploy' and 'destroy' methods on the ServiceDeployApi controller class. 
- [ ] Extend the deploy and destroy methods with parameters - parentOrderId and workflowId. These parameters must be hidden using `@Parameter(hidden = true)`. This means the parameters are not visible in the REST API. but will be used only by our internal calls. 
- [ ] Use the parentOrderId and workflowId to generate SERVICE_ORDER entry with extra details but does the same steps as regular deploy and destroy. 
- [ ] Take UserId from the parentOrderId
- [ ] Delete all extra methods written specially to handle migration requests. 
sequence diagram - https://www.mermaidchart.com/raw/a964c8cb-e99e-4040-bcdc-656593c43a31?theme=light&version=v0.1&format=svg

**Comment by baixinsui** [comment]
I will take it
