### ISSUE TITLE
change property names in DeployResult more clear

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2067]
https://github.com/eclipse-xpanse/xpanse/blob/632461725135d991c2fb3bd64ec13781be827676/modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployResult.java#L23

- [ ] rename properties -> outputProperties
- [ ] privateProperties -> deploymentGeneratedFiles

**Comment by Alice1319** [comment]
I’ll take this.
