### ISSUE TITLE
change how we find the files generated by the deployer

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2068]
Currently we only exclude files with the mentioned in the list here -> https://github.com/eclipse-xpanse/xpanse/blob/ea7914db1bcb079f390bfc33fb3aae16de32136c/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalExecutor.java#L38

This list can be controlled and maintained but the files that comes from the service vendor scripts  cannot be always checked. For example, if there is a shellscript or python script in the repo. 

- [ ] Exclude the files as before from the exclusion list. 
- [ ] Check the existing files before deployment and ignore all files that were already part of the deployment. 
- [ ] Changes to local TF and Opentofu deployment and also to terraform-boot and tofu-maker.

**Comment by baixinsui** [comment]
I will take it.
