### ISSUE TITLE
When choose 'not selected' availability zone to deploy, backend not return error, deploying status always show deploying.

### ISSUE THREAD

**Issue by Alice1319** [eclipse-xpanse/xpanse#2078]
![image](https://github.com/user-attachments/assets/8718f9e9-e756-4689-827b-0b88ebf9a56b)

polling 3 minutes:
![image](https://github.com/user-attachments/assets/d4618a0b-0964-4526-a058-b35faa868a16)

backend always polling , the status not be changed.
![image](https://github.com/user-attachments/assets/73c42377-5b55-45af-811f-9aaca5ff8683)

polling 6 minutes:
![image](https://github.com/user-attachments/assets/55be415a-0283-4634-a097-20c122e05484)

**Comment by Alice1319** [comment]
> @Alice1319 i cannot reproduce this issue. can you please attach the complete server log?
sure

**Comment by swaroopar** [comment]
@Alice1319 is this problem still there, otherwise we can close this issue ?

**Comment by Alice1319** [comment]
not reproducible
