### ISSUE TITLE
No error message stored to SERVICE_ORDER when destroy fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2080]
When a destroy request fails, no error is stored to SERVICE_ORDER. Please find attached logs.

[error-log.txt](https://github.com/user-attachments/files/17557718/error-log.txt)

![image](https://github.com/user-attachments/assets/e5bc4e2e-2ffe-473d-8451-1fbc02c943f5)

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
![image](https://github.com/user-attachments/assets/76ca6edd-f451-4e24-8a31-bcedfde29cf0)
 this issue has been fixed, pls close it.

**Comment by Alice1319** [comment]
![image](https://github.com/user-attachments/assets/a89eb5b0-2ad2-464d-9f62-c03a52cb01bb)

destroy error msg saved to order table after destroy failed.
