### ISSUE TITLE
destroy status not updated when order is completed

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2081]
When order fails or succeeds, the alert is correctly displayed but the status remains 'Destroying'. This was working before and is destroyed with the recent changes. 

![image](https://github.com/user-attachments/assets/63062322-29de-4c55-b80b-e9c906299514)

![image](https://github.com/user-attachments/assets/e43eaafc-85dc-48fd-a1de-c783ee1f824b)

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
I'll take this.
