### ISSUE TITLE
Add full order result information to service_order table and ServiceOrderStatusUpdate

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2082]
- [ ] Rename enum `ResultType` to `ErrorType` and remove `SUCCESS` from it. (We never use SUCCESS or return this enum in case of successful execution)
- [ ] Rename type `Response` to `ErrorResponse`
- [ ]  Remove property `success` from `Response` type. (It is always set to false in our case)
- [ ] `ServiceOrderStatusUpdate` - change property errorMsg to 'error' and type `ErrorResponse`
- [ ] In SERVICE_ORDER entity, change the `ERROR_MSG` column to type 'Response' and also rename column to `ERROR`
- [ ] Compile interface on UI and make necessary changes to display correct error response from `ServiceOrderStatusUpdate

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
I'll take this.
