### ISSUE TITLE
change migration order polling to regular order polling APIs

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2086]
After the implementation of https://github.com/eclipse-xpanse/xpanse/issues/2057  userstory, the migration order will also use the unified order tracking implemented xpanse. 

- [ ] Switch UI to use the standard order polling response. 
- [ ] Test migration

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
I’ll take this.
