### ISSUE TITLE
Optimize method for initializing cache of  versions of the deployer tool

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#2089]
When the network is not connected or the speed is slow, obtaining the deployment tool version from  the endpoint `https://api.github.com` will can take a long time (about 25 min), and this method uses `@PostConstruct`  which make the application start slowly, looks like the application cloud not be started normally. This must be optimized.
 The following changes to the method:

- [x] Move the initialization method after the application is successfully started.
- [x] Due to the GitHub SDK used not providing a setting for connection timeout duration, add network connection check and customize timeout duration.
- [x] Output necessary logs. such as start, end ,error
- [ ] Update this method in xpanse, terraform-boot,tofu-maker

**Comment by baixinsui** [comment]
I will take it.

**Comment by qigaoneng** [comment]
LGTM
