### ISSUE TITLE
change SERVICE_TEMPLATE structure 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2098]
- [x] Rename to ServiceTemplateRegistrationState Enum – IN_PROGRESS, ACCEPTED, REJECTED 
- [x]  add new boolean columns – IS_UPDATE_PENDING – Set this is true when update request is received and then set it back to false when UPDATE review is completed.
- [x] Add new COLUMN – AVAILABLE_IN_CATALOG – boolean – will be set to true when the service is accepted for the first time. Will be set to false when de-registered, or update is submitted with flag ‘isRemoveCurrentTemplateFromCatalog’ true.

**Comment by baixinsui** [comment]
I will take it
