### ISSUE TITLE
Add new SERVICE_TEMPLATE_HISTORY TABLE

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2099]
- [ ] CHANGE_ID (UUID) as the PK
- [ ]  SERVICE_TEMPLATE_ID – FK with One to Many
- [ ] SERVICE_TEMPLATE_REQUEST – Store the OCL in the request as it is into CLOB column. 
- [ ] STATUS enum ServiceTemplateChangeStatusEnum – IN_REVIEW, ACCEPTED, REJECTED -> we simply set it to ACCEPTED for unregister  
- [ ] REQUEST_TYPE – REGISTER, UPDATE, UNREGISTER, REREGISTER
- [ ] REVIEW_COMMENT – STRING → Move from the SERVICE_TEMPLATE table.
- [ ] BLOCK_TEMPLATE_UNTIL_REVIEWED – Default false. Value will be set only the ‘UPDATE’ process to true if provided in the ‘UPDATE’ request. This is a read only value. Will not be changed. 
-

**Comment by baixinsui** [comment]
I will take it
