### ISSUE TITLE
Implement changes to update service template method

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2101]
![image](https://github.com/user-attachments/assets/786ca528-75e8-4db5-96c7-9025922499dd)

- [ ] Add entry additionally to SERVICE_TEMPLATE_HISTORY table with REQUEST_TYPE - UPDATE
- [ ] SERVICE_TEMPLATE table -> set is IS_UPDATE_PENDING  to true if auto-approval is false.
- [ ] Add new boolean to update URI – isRemoveServiceTemplateUntilApproved
- [ ] If true, the service template is not returned to the customer for ordering services until the update is reviewed and approved
- [ ] If false, the already approved previous service template continues to be available for the end customer to order new services.
- [ ] No update should be allowed if ServiceRegistrationState still in IN_REVIEW.

**Comment by baixinsui** [comment]
I will take it
