### ISSUE TITLE
Changes to re-register, un-register and delete service template methods

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2108]
Re-register

- [ ] Set AVAILABLE_IN_CATALOG to true directly. 
- [ ] Write HISTORY entry with status ‘REVIEW_PENDING’ to ACCEPTED directly and TYPE ‘REREGISTER’
- [ ] Should be allowed only when the AVAILABLE_IN_CATALOG  is false and ServiceRegistrationState is ACCEPTED.
- [ ] Re-register works only for already registered and accepted services. So additional review not required. 

Unregister

- [ ] Set AVAILABLE_IN_CATALOG to false. 
- [ ] Write HISTORY entry with status ‘REVIEW_PENDING’ or ACCEPTED based on the auto-approval status and TYPE ‘UNREGISTER
- [ ] Should be allowed only when the AVAILABLE_IN_CATALOG  is true and ServiceRegistrationState is ACCEPTED.

Delete

- [ ] To also delete HISTORY table. 
- [ ] Allowed for all states of the ServiceRegistrationStatus. but the AVAILABLE_IN_CATALOG must be false. Otherwise always first un-register must be executed and then delete.
- [ ] As before, delete must be rejected if there are active services based on the service template.

**Comment by baixinsui** [comment]
I will take it
