### ISSUE TITLE
highlight ISV name in each service

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2117]
Currently the ISV name is not shown in any of the end user views but this is an important piece of information.

- [ ] ISV name must be highlighted using the icon <ShopOutlined /> . The name can be also put in a tag. 
![image](https://github.com/user-attachments/assets/5c0251b9-1e60-4231-bd88-e01eec8e8056)

- [ ] Same must be also added in the below places
![image](https://github.com/user-attachments/assets/b51dfc6a-9212-4f6e-9292-4502745dd6b2)
![image](https://github.com/user-attachments/assets/f72f7447-a1f0-4e2d-a4e4-09c45216603e)

We can review the designs during implementation.

**Comment by Alice1319** [comment]
> Currently the ISV name is not shown in any of the end user views but this is an important piece of information.
> 
> * [ ]  ISV name must be highlighted using the icon  . The name can be also put in a tag.
>   ![image](https://private-user-images.githubusercontent.com/54129659/385404248-5c0251b9-1e60-4231-bd88-e01eec8e8056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTgxOTcsIm5iZiI6MTczMzgxNzg5NywicGF0aCI6Ii81NDEyOTY1OS8zODU0MDQyNDgtNWMwMjUxYjktMWU2MC00MjMxLWJkODgtZTAxZWVjOGU4MDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YjRlOTgyOGRjZTJkZjI0NjQzN2RmYjc2OGRhMjQ1YWFiMzVkMjllZDc2MjNmNWMyN2E4MjFiZTAxZTlmYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PA5L5BuyLJlyb1W3gUfqx431JP5SgucjDA8ZgryjocI)
> * [ ]  Same must be also added in the below places
>   ![image](https://private-user-images.githubusercontent.com/54129659/385404506-b51dfc6a-9212-4f6e-9292-4502745dd6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTgxOTcsIm5iZiI6MTczMzgxNzg5NywicGF0aCI6Ii81NDEyOTY1OS8zODU0MDQ1MDYtYjUxZGZjNmEtOTIxMi00ZjZlLTkyOTItNDUwMjc0NWRkNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNTA0N2ZkMGVlYjdkOWFkNjVlZjA0YjFlZWUyZTY2NjA4NDM0M2VmYmYzNjcxODBhOWEzMjA3MmZkOGU3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q5hJzGKSBTpfPBO3yM3vAJhev7d0GSjD2X_cF8hrkco)
>   ![image](https://private-user-images.githubusercontent.com/54129659/385404966-f72f7447-a1f0-4e2d-a4e4-09c45216603e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTgxOTcsIm5iZiI6MTczMzgxNzg5NywicGF0aCI6Ii81NDEyOTY1OS8zODU0MDQ5NjYtZjcyZjc0NDctYTFmMC00ZTJkLWE0ZTQtMDljNDUyMTY2MDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4MDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMzg4NWNjNzQ2MjVjYjM5OWI4MzNmMWRjOWE5MDY0MzU1NGRkM2E5ZjYyYjE2MWU3YWRlYjBmYmJmZjBmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WaJVKN8E1TTyYLOs1W_gLgvYQbjVk-u_K-ZhkG8rciU)
> 
> We can review the designs during implementation.

namespace shoe like vendor - ${namespace}
