### ISSUE TITLE
Integrate  getStoredTaskResultByRequestId in xpanse

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2130]
- [ ] Add a new mandatory column 'HANDLER' to the SERVICE_ORDER.
- [ ] Values for HANDLER -> TERRAFORM-LOCAL, TERRAFORM-BOOT, OPENTOFU-LOCAL, TOFU-MAKER, INTERNAL, WORKFLOW, AGENT, PLUGIN
- [ ] Update all inserts for SERVICE_ORDER to have this value. 
- [ ] Add new configuration - max.service.order.processing.duration.in.seconds=180
- [ ] Whenever there is an API call that returns 'DeployedService' or DeployedServiceDetails and when the corresponding service is stuck in DESTROYING/DEPLOYING/MODIFYING for more than the above configuration time.. (order created time > the max processing duration) and if the order handler is TERRAFORM-BOOT or TOFU-MAKER, then call the newly added service in #2079 and #2129 respectively to fetch the latest status.  If they return an exception (Already returned or not found), then set the order status to ERROR with the error message from API and set the ServiceDeploymentState to MANUAL_CLEANUP_REQUIRED. 
- [x] If API returns 204 (implemented in #2131), then return the status same as what is stored in xpanse DB

**Comment by WangLiNaruto** [comment]
let me do it
