### ISSUE TITLE
validate value for fix_env and fix_variable variables

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2183]
for deployment variables in OCL which have kind - fix_env and fix_variable, we must always validate that the default value is provided by the ISV. 

- [ ] Add validation
- [ ] throw error  - MandatoryValueMissingForFixedVariables and return the variables which have values missing.

**Comment by Alice1319** [comment]
I'll take this.

**Comment by baixinsui** [comment]
I will take it.

**Comment by Alice1319** [comment]
I'll take this
