### ISSUE TITLE
rename namespace field to 'serviceVendor'

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2188]
Currently the field 'namespace' is not very self-explanatory in the context of xpanse. We will need to rename it to something that exactly represents the underlying meaning of the word.

- [x] in the OCL - change this value to serviceVendor
- [x] in the oauth metadata - the name of the field must be 'isv'
- [x] Update samples. 
- [x] Update UI
- [x] Update xpanse-iam
- [x] Update documentation in xpanse-website

**Comment by baixinsui** [comment]
I will take it
