### ISSUE TITLE
allow multiple files to be directly mentioned in OCL

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2195]
Currently OCL supports only file in 'deployer'. We must change this to allow multiple files. 

- [x] change deployer field to a Map - key must be file name (with correct file extension) and value must be the file content. 
- [x] change deployment module to directly create files with the names from the OCL instead of the fixed names. 
- [x] Test if the scripts can contain for example a shell script, a python script. 
- [x] Update samples.

**Comment by baixinsui** [comment]
I will take it
