### ISSUE TITLE
rename IS_UPDATE_INPROGRESS to IS_REVIEW_INPROGRESS

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2197]
Currently we have a flag IS_UPDATE_INPROGRESS' but this flag does not manage any other requests that are inprogress. 
For example, a 're-adding to catalog' process if pending of review, then the ISV must know that there is some request which is in-progress. 

- [x] rename IS_UPDATE_INPROGRESS to IS_REVIEW_INPROGRESS
- [x] Update this flag for any request which is in status IN_REVIEW
- [x] Rename the data model property also to reviewInProgress

**Comment by baixinsui** [comment]
I will take it
