### ISSUE TITLE
changes to re-register and unregister methods

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2198]
Registration - This term means the service is for the first time submitted to a cloud provider. When the registration request is approved, 
then the service is added to catalog for the first time. Registration process ends when the service is added first time to the catalog.
So the terms re-register and de-register makes less sense

changes to unregister
- [x] rename method to unregister to 'removeFromCatalog'
- [x] RequestType to be renamed to ‘REMOVE_FROM_CATALOG’

changes to re-register

- [x] Allowed only when service registration state is APPROVED, 
- [x] rename method to 'reAddToCatalog'
- [x] RequestType to be renamed to ‘RE_ADD_TO_CATALOG’
- [x] Allowed only when service registration is approved and isAvailableInCatalog is false and IS_REVIEW_INPROGRESS is false. 
- [x] when re-register is sent for review - then update IS_REVIEW_PENDING to true.

changes to delete
- [x] Allowed when service is ‘NOT_IN_CATALOG’ is true.

**Comment by baixinsui** [comment]
I will take it
