### ISSUE TITLE
fix error message in deployment

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2201]
With the recent changes, the error message for deployment shows a full JSON. This must be fixed. 

- [ ] Display only error type and error details. Details must be a unsorted list. Like it was before. 
- [ ] 'back button' must be enabled when there is a failure. 

![image](https://github.com/user-attachments/assets/6f99368b-5758-4290-94b1-c2fe2c088de7)

**Comment by Alice1319** [comment]
I'll take this.
