### ISSUE TITLE
issues with review component for CSP user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2202]
- [x] The approve and reject modal accepts even empty string. It must be a mandatory field and user must enter some text. 
- [x] buttons remains enabled when there is a failure in submitting the review. but when we click on the buttons, nothing happens. 
- [x] Its also better we move the alert above buttons. 

![image](https://github.com/user-attachments/assets/b84da779-81b3-4c26-ab88-854d59dc7bb0)

![image](https://github.com/user-attachments/assets/25b0d4d0-2835-42de-b7fe-1e4dc879a4a5)

**Comment by Alice1319** [comment]
I'll take this
