### ISSUE TITLE
change service configuration related data model names  to common names

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2206]
We plan to reuse the design which we did for the service configuration implementation for other usecases such as service actions. Hence must change the namings to something generic. 

- [x] Rename ServiceConfigurationManage to ServiceChangeManage
- [x] Rename ConfigManageScript to ServiceChangeScript - action
- [x] Rename ServiceConfigurationParameter to ServiceChangeParameter
- [x] Rename configManager to changeHandler
- [x] Field names in OCL for serviceConfigurationManage can be same as before. Only model names will change.

**Comment by WangLiNaruto** [comment]
let me do it
