### ISSUE TITLE
change DB structure to store service actions

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2208]
- [ ] Rename SERVICE_CONFIGURATION_CHANGE_DETAILS to SERVICE_CHANGE_DETAILS
- [ ] Rename column configManager column to ‘CHANGE_HANDLER’
- [ ] SERVICE_ORDER table – remove NEW_CONFIG_REQUEST column and NEW_DEPLOY_REQUEST column. Insert all request bodies to REQUEST_BODY column.

**Comment by WangLiNaruto** [comment]
let me do it
