### ISSUE TITLE
Error details not shown in alert when registration request fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2213]
When registration fails, the error details are not displayed correctly. this seems to broken with the recent changes. 

![image](https://github.com/user-attachments/assets/b72760a6-b670-4049-a10b-51714a73aeda)
 Error received from backend in this case -
20241214 16:34:29.430 [http-nio-8080-exec-8] INFO  o.e.x.m.logging.CustomHttpLogWriter [702eb63b-b6d1-41d0-a3a3-56c4afd5affb] [] []- Response: 400 Bad Request Duration: 8ms  {"errorType":"Plugin Not Found","details":["Can't find suitable plugin for the Csp RegioCloud"]}

**Comment by Alice1319** [comment]
I‘ll take this.
