### ISSUE TITLE
change names of service template states again

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2232]
The more we use and discuss the about the service template states, we find better ways of naming them.

- [ ] register -> submits a new service and when approved, it will be published to catalog - nothing to do. 
- [ ] update -> updates an existing service and when approved, the updated service template will be published to catalog.
- [ ] unpublish - remove the service template from catalog. -> rename - removeFromCatalog to unpublish
- [ ] re-publish - publishes the same service template to catalog again -> rename reAddToCatalog to republish. 
- [ ] Change enums, method names, etc.

**Comment by baixinsui** [comment]
I will take it
