### ISSUE TITLE
Replace DB entities with View objects in REST API

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#233]
Currently DB entities are directly exposed on the REST API. 
We must replace this with view objects and add all OpenAPI annotations  - Eg., schema, bean validations, etc

**Comment by baixinsui** [comment]
It's a good idea. I think we should create view entities replace all the DB entities which we  are directly exposing on the REST API, and add openAPI annotations to these new create view entities.  I will do this.
