### ISSUE TITLE
Return OpenAPI URL of the service in response objects with HATEOS

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#265]
Return the OpenAPI URL of the services in register response and also in all other relevant view objects.
1. These fields must be links according to HATEOS concept. 
2. Check if spring has support of handling links in HATEOS based fields when the REST API is hosted behind load balancers and add required configuration for it..

**Comment by baixinsui** [comment]
It's a good idea. I will do it.
