### ISSUE TITLE
OpenApi generation for registered services fail when application started from jar

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#283]
When the application is started via spring boot fat jar, then the open API generation is failing.

Currently the lib is not copied into the spring boot jar.

17:08:48.683 [thread-pool-1] ERROR o.e.x.orchestrator.utils.OpenApiUtil []- Error: Unable to access jarfile ./lib/openapi-generator-cli.jar
17:08:48.689 [thread-pool-1] ERROR o.e.x.orchestrator.utils.OpenApiUtil []- Create service openApi html file failed.Error: Unable to access jarfile ./lib/openapi-generator-cli.jar

**Comment by baixinsui** [comment]
I will fix it.
