### ISSUE TITLE
Refactor API URIs to have uniform pattern

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#285]
- [ ] Start all APIs with /services
- [ ] Register APIs to have URI pattern 
           - /services/register - POST and GET
           - /services/register/{id},
           - /services/register/update
           - /services/register/delete (for unregister)
           - services/register/category/{categoryName}

- [ ] To deploy services and to list deployed services
      - /services/deployed
      - /services/deployed/{id}
      - /services/available
      - /services/deploy
      - /services/destroy
- [ ] Service categories -> /services/categories

**Comment by baixinsui** [comment]
I will do it.
