### ISSUE TITLE
Turn to call the `/services/avaliable/xxx` API in the pages of the end-user

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#289]
- [ ] Turn the pages of the end-users to call the  `/services/avaliable/xxx` API

 
As the end-user used the `/register` API to get all the services available, It will let the end-user see all the OCL definitions that the Software-Vendor not want to.
so we create the `/services/available/xxx` for the End-Users, only responding the information necessary.

**Comment by Alice1319** [comment]
I‘ll take this.
