### ISSUE TITLE
Design for the Monitor of xpanse

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#317]

**Comment by Alice1319** [comment]
@iskey @swaroopar @WangLiNaruto 
This is the design page for Monitor, please take a look.

![image](https://user-images.githubusercontent.com/42802200/233817199-958a1a2f-58a5-484d-a86a-d9d45d0e9a68.png)
![image](https://user-images.githubusercontent.com/42802200/233817209-939c98ff-1275-43bd-b08c-ba5ccc9c2cde.png)
