### ISSUE TITLE
Design the Credential Center business logic

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#333]
- [x] Draw a diagram for the business logic.

**Comment by baixinsui** [comment]
I will do it.

**Comment by baixinsui** [comment]
![OrchestratorApi_structure-0](https://user-images.githubusercontent.com/121531362/236813443-c1d440e0-8bd1-4a6c-a472-be287caf91c3.svg)

**Comment by baixinsui** [comment]
![OrchestratorApi_structure-0](https://user-images.githubusercontent.com/121531362/236975959-754587db-a505-4ed8-b361-71542a9ea42e.svg)
