### ISSUE TITLE
Delete old getMetrics method

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#396]
Remove the old getMetrics method.

https://github.com/eclipse-xpanse/xpanse/blob/0a50e2356071a7d2a7233e8411d67d75343bcb6f/modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java#L69

To be done once the new methods are working.

**Comment by jinyangyang222** [comment]
I willl take this.
