### ISSUE TITLE
Credentials Management UI - add new credentials

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#424]
On the "Credentials Management" UI -> display a new "Add Credential" button which has the following functionality

- [ ] Open a new pop-up
- [ ] Provide CSP dropdown
- [ ] Based on the CSP dropdown selected -> call the "getCredentialCapabilitiesByCsp" method in the API and populate the "Type" list based on the `type` in the response object list entries. 
- [ ] based on the `type` selection, display the form fields for the underlying "CredentialVariable"
- [ ] Fields with `isSensitive` to be masked while entering values.
- [ ] Field description to display text from  `CredentialVariable.description` field.
- [ ] call "addCredential" method on clicking "create" button at the end.

Note - Implementation can probably blocked by the bug #423

**Comment by WangLiNaruto** [comment]
let me do it
