### ISSUE TITLE
Credentials Management UI - update credential

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#426]
- [ ] On the credentials table, the update button must open-up a popup form with fields required to update credentials.
- [ ] Use the form implemented for adding credential in user story #424 
- [ ] Pre-fill the form with CSP (read only), Type(read only) and existing credential variable values. 
- [ ] On click on "update", call the "updateCredential" method. 
- [ ] Fields with `isSensitive` to be masked while entering values.
- [ ] Field description to display text from  `CredentialVariable.description` field.
- [ ] Ensure reusability of components created in #424

Note - Depends on #423 and #424

**Comment by WangLiNaruto** [comment]
let  me do  it
