### ISSUE TITLE
Monitor UI - update  to use new metrics API for fetching 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#433]
We currently provide options in the UI to load metrics data for different time intervals from the past but this feature is not yet using the latest API.

- [ ] For all options other than `last minute`, use the "from" query filter. This API call return more than one metrics. 
- [ ] For `last minute` option, will have a new `query parameter` (see #395 ). This API call will return only one metric.

**Comment by Alice1319** [comment]
I'll take this
