### ISSUE TITLE
CredentialsApi - Add method to GET credentials stored

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#447]
In the credentials API, currently we do not have any method which returns the configured credentials for a CSP by an Xpanse user

- [x] New GET method - `getCredentials`
- [x] Mandatory query parameters - `csp`, `xpanseUser`
- [x] fields with `isSensitive` must have the value masked in the response. Return value as `*****` in such cases.
- [x] for credential variables whose value is null - we must read the value from OS environment variables and return it. So that the user knows which value would be used during the deployment or monitoring. This will also provide the end user an option to override with his custom value when the user finds out that this value is wrong.

**Comment by jinyangyang222** [comment]
I'll do this.

**Comment by jinyangyang222** [comment]
I'll do this.

**Comment by jinyangyang222** [comment]
@swaroopar Hi swaroopar,The method  -getCredentials you mentioned above is the same as the existing method -getCredentialDefinitionsByCsp, but for the Wang Li front-end, it now requires a method that only passes the userName parameter.

**Comment by swaroopar** [comment]
Hi @jinyangyang222, 
ideally `getCredentialDefinitionsByCsp `-> will only return the definitions by Csp, which is nothing but the type of credentials supported by CSP. This is not user specific and it will not have the actual credentials configured by the end user. 

the new  `getCredentials` will now returned the credentials configured by the end user for a CSP and for a specific type. 
The response model for this also depends a bit on #423

**Comment by swaroopar** [comment]
@jinyangyang222  in getCredentials -> we do not need the definition. We need the values of the credential variables for that specific user.

**Comment by swaroopar** [comment]
@jinyangyang222 we are using  GET method internally (here)[https://github.com/eclipse-xpanse/xpanse/blob/f0a113902fa70ef0edcf0045d43a95770d3a14a2/modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java#L179]
We must extend this to have credential type parameter and expose it  via REST API. 
Also add type from all current calling methods.

**Comment by jinyangyang222** [comment]
okay,thank you @swaroopar,I will do this.

**Comment by swaroopar** [comment]
Hi @iskey 
The internal [method](https://github.com/eclipse-xpanse/xpanse/blob/f0a113902fa70ef0edcf0045d43a95770d3a14a2/modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java#L179) is currently called without credential type.  and the method simply takes the first available credential. This must be changed. 
I believe the credential type must be decided by the calling functionality.. for example service deployer might need its own type of credential and monitoring might need its own type of credential for the same CSP. 
If you agree to this, then @jinyangyang222  can change this with the same PR or we make the change before this PR.

**Comment by iskey** [comment]
Hi @swaroopar, of course, It is correct that the calling functionality must decide the credential type,
I agree. Please go ahead.

**Comment by swaroopar** [comment]
> Hi @swaroopar, of course, It is correct that the calling functionality must decide the credential type, I agree. Please go ahead.

@jinyangyang222 this part is done. Changes are merged to master.
