### ISSUE TITLE
FlexbileEngine plugin - exception in client generation ignored

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#487]
In the below code, all the exception from a method call is simply caught and ignored. 
This will only make the method return null which will cause further errors in the calling method. 
https://github.com/eclipse-xpanse/xpanse/blob/cee4652b85ab48c6b3dd855bddc1bdc7d8d6e335/plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/MetricsService.java#L111

**Comment by baixinsui** [comment]
I will take this.
