### ISSUE TITLE
Enable spring security with oauth2

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#562]
- [ ] Add new spring profile called - `zitadel`. This is necessary to ensure that we can enable security only when the feature is fully available and also switch between different identity providers. 
- [ ] Add new `security` maven module under `modules`.
- [ ] Add OIDC (oauth2) based authentication using spring security. 
- [ ] Security bean to be initialized only when `zitadel `profile is activated.
- [ ] Use 'OpaqueToken'
- [ ] Protect all `/xpanse/` URI with oauth. 
- [ ] Return 401 if authentication fails. 
- [ ] Document how to start the application by passing `client-secret` variable.

Note - Spring security filter need not do any redirection. It must  only validate the provided authorization header and return error 401 if the token validation fails. 
Depends on  #563

**Comment by baixinsui** [comment]
I will take it.
