### ISSUE TITLE
Start automation of IdP initial configuration

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#564]
We need to automte the initial IdP configuration process. 
1. Prepare a script which does API calls and configures the following objects on Zitadel -
    - Organization - `eclipse-xpanse`
    - project - `eclipse-xpanse`
    - Roles - user, admin, csp
    - Brand configuration - logo, etc
2. Automation must work on windows and linux. 
3. Automation must work for local dev setup as well as remote instances.
4. Document the same in on website.

P.S - we can discuss what is the best way to do it. Either API calls or we can also consider using the Zitadel terraform provider. 
If we use terraform provider, we can also consider provider a github action which executes the scripts.

**Comment by swaroopar** [comment]
@jinyangyang222 as discussed, please consider the following points. 

1. Refer to the current XPANSE organization in testbed and the scripts must ensure the same configurations are considered for the terraform script. 
2. In this user story, we can consider only organization, project, branding, roles 
3. For application - we have other user stories #563 #573

**Comment by jinyangyang222** [comment]
Okay, I understand
