### ISSUE TITLE
REST API - Enable RBAC

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#567]
- [ ] Add 3 roles to `eclipse-xpanse` project on  Zitadel - admin, user, csp
- [ ] Add authorization required on API - at class level or at method level
- [ ] Validate the 'token' claims contains the list of roles allocated to user under claim name `urn:zitadel:iam:org:project:roles` - https://zitadel.com/docs/apis/openidoauth/claims
- [ ] Proceed only when the required role is available in the list of role the user has in the claim `urn:zitadel:iam:org:project:roles`.
- [ ] If role is allowed to user, then return 403 error.
- [ ] Ensure the role based authorization is executed only when `zitadel` profile is enabled.
- [ ] If no role is received in the claims, then assume `user` roles.

Note - we might have to use the customizer for extracting roles - https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/opaque-token.html#webflux-oauth2resourceserver-opaque-authorization-extraction

**Comment by baixinsui** [comment]
I will take it.
