### ISSUE TITLE
Prepare OAUTH login for UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#572]
- [ ] Implement Oauth login for UI. Example - https://zitadel.com/docs/examples/login/react
- [ ] Ensure the new logic is triggered only when the feature is enabled  - add a feature flag to the properties file.
- [ ] when the new feature is enabled, any page access without login must redirect to oauth2 login page. And after login, the page must route back to previously accessed page.
- [ ] By default request the following scopes -> `openid` `profile` and `email`
- [ ] Display user's full name and email address on top right corner of the header.
- [ ] provide configuration properties that can be read from environment variables for - oauth provder_url, redirect_url, client_id
- [ ] Add documentation
- [ ] We can store the access token in local storage.

Depends on #573

**Comment by Alice1319** [comment]
I'll take this.
