### ISSUE TITLE
Add identity provider to healthcheck method

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#605]
When Authentication is enabled, 
the healthcheck method must additionally check the status of the IdentityProvider and return its status

- [ ] Extend `SystemStatus` object with a new type called `IdentityProviderStatus`
- [ ] `IdentityProviderStatus` -> endpoint: string, status: HealthStatus, ProviderType: new Enum, with one value -> Zitadel
- [ ] endpoint -> should return whatever is read from the spring properties.
- [ ] HealthStatus should be based on response of https://zitadel.com/docs/apis/observability/health

**Comment by baixinsui** [comment]
I will take this.
