### ISSUE TITLE
Add Zitadel documentation for local development

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#614]
The following must be added to `xpanse-iam` repo under directory - https://github.com/eclipse-xpanse/xpanse-iam/tree/main/zitadel

- [ ] new folder `local`
- [ ] Add steps on how to start the docker containers for Zitadel
- [ ] How to run the configuration scripts.
- [ ] How to use this xpanse and API

Please note - this user story is not only about documentation. We must test the process and then document all steps.

**Comment by baixinsui** [comment]
I will take it.
