### ISSUE TITLE
Display HealthCheck status in UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#618]
For users with 'admin' role, a new page must be added

- [ ] Use the new 'HealthCheck' method to retrieve health status of the system and all backend systems
- [ ] Display a table for all backend system status. 
- [ ] Status column should in green if backend is OK. otherwise 'NOK' should  be red. 

This can be implemented only after PR #613 is merged.

**Comment by Alice1319** [comment]
I‘ll take this
