### ISSUE TITLE
opening service openAPI fails with 401

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#621]
We currently provide an option to open the the OpenAPI documentation of the registered service from UI.  But this is not working after authentication was introduced. 

We currently use `window.open()` to open the API page but it looks like this method does not allow providing authentication header .
https://stackoverflow.com/questions/35332673/is-that-possible-to-send-header-information-in-window-openurl-method

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/116c16db-3ccf-4cc6-871d-ff3446750aee)

**Comment by baixinsui** [comment]
The generated openAPI  should be without  authentication  as  openAPI on Swagger-UI.

**Comment by swaroopar** [comment]
@baixinsui I think so too. Anyways the user has to login to get the ID of the service.

**Comment by baixinsui** [comment]
Ok. I will take it.
