### ISSUE TITLE
Validate the current login user in the user related APIs

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#623]
- [ ] Get the user info directly from the IAM.
- [ ] remove username field in request body
- [ ] rename DB column to USER_ID and store the `sub` field which we  get from the token.
- [ ] Validate the user parameters in the API with the current token in the request header.
- [ ] Same for add credential and credential key. User IDs must be used for storing credential cache.

**Comment by baixinsui** [comment]
I will take it.

**Comment by baixinsui** [comment]
@swaroopar @iskey If the value of parameter 'userId' in the API request is different from the value of 'sub' get from token in the request header. What should we do in the validate method? throw an exception or use the value of 'sub' to overwrite the value of parameter 'userId' directly?

**Comment by swaroopar** [comment]
We must remove the user name or user id parameters from API

**Comment by baixinsui** [comment]
@swaroopar remove the userId from API.  How to get user info when oauth2 is disabled?

**Comment by swaroopar** [comment]
@baixinsui no, the security will remain enabled. What I meant is.. all username related fields in the API must be removed. 
We must read the 'sub' of the user from the token and write it to the DB during services ordering.. and similar logic for GET also. 
Same needs to be done for credential cache as well. We must store the sub instead of the name. 
No name or personal details must be stored in our system.

**Comment by baixinsui** [comment]
When user run the application without profile 'zitadel', How to get 'sub' as userId?

**Comment by swaroopar** [comment]
@baixinsui good point. I missed it.  Yes, we must update doc and if possible, even make zitadel profile active by default.

**Comment by swaroopar** [comment]
@baixinsui good point. I missed it. yes, we must enable zitadel it by default. we can update the necessary docs.

**Comment by baixinsui** [comment]
@swaroopar Ok. @iskey What do you think about this?

**Comment by iskey** [comment]
@baixinsui ,I suggest we remove the username from the request body first, then we can consider the fallback solutions without IAM after that.
