### ISSUE TITLE
switch to react-query for all API calls in credential components

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#626]
Similar to #622, switch all API calls in credential components to react-query. 

- [ ] remove all direct API calls
- [ ] read status of request, response, error from react-query hooks.

**Comment by Alice1319** [comment]
I'll take this

**Comment by Alice1319** [comment]
@WangLiNaruto

**Comment by WangLiNaruto** [comment]
I will fix it
