### ISSUE TITLE
Exploratory Tests for Xpanse runtime

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#637]
We have been testing happy cases during development and as part of unit test. But this is not sufficient. We need exploratory tests to check if the system works as intended for all use-cases. This must be executed with the single intention of breaking the system. 

- [ ] Test API for all possible combinations of the data model. Eg., Requests to API by sending only mandatory fields. To ensure all optional fields are really optional, sending corrupt data, sending different characterset data, edge cases, etc
- [ ] Test API for exceptions. Check if correct exceptions are returned. 
- [ ] Store API test suite - as a SoapUI project or as Postman collection for running it next time or by another contributor. This can be uploaded to "xpanse-relops" repo.
- [ ] Check logs for the request executed - is any sensitive data logged, is any duplicate data logged, is any log format broken, does all logs have the unique UUID to track. 
- [ ] Check if data is stored correctly - do a GET after POST or PUT to check if the data matches. 
- [ ] Security tests -  Validate authorization layer. 
- [ ] Open an issue for each bug found and label it as `bug`.

**Comment by baixinsui** [comment]
I will join in it.

**Comment by jinyangyang222** [comment]
I will join in it.

**Comment by jinyangyang222** [comment]
Hi Swaroopar @swaroopar ,About Task 3, Postman currently does not have a free version. If we use it for testing and upload the test set to the 'xpanse repos' repository, Would this be inappropriate? And Yichao recommended a free tool,Can you please refer to what we should do.
https://insomnia.rest/pricing

**Comment by swaroopar** [comment]
@jinyangyang222 postman is free atleast for the features we need. Otherwise pls also consider SoapUI https://www.soapui.org/tools/soapui/

**Comment by jinyangyang222** [comment]
> @jinyangyang222 postman is free atleast for the features we need. Otherwise pls also consider SoapUI https://www.soapui.org/tools/soapui/

ok.

**Comment by swaroopar** [comment]
closing. Tests have been performed.
