### ISSUE TITLE
API- Add Credential error when filling custom name not defined name.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#645]
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/c75dfa0c-8991-4419-a6a3-841234e9d7b4)

![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/e204a50f-a7b8-4413-8d61-40cd0

Add Credential error when filling custom name not defined name 'AK_SK'，the name shoud be full with the value 
name in the  return data of API "/credential/capabilities?type={type}"
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/32f481c1-cb91-4546-a45c-5af47732ecf4)

**Comment by WangLiNaruto** [comment]
I will fix it
