### ISSUE TITLE
UI- Remove the Parameter 'username' and the filed 'xpanseUser' from all APIs

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#648]
![chrome_59P05zJvj5](https://github.com/eclipse-xpanse/xpanse/assets/121531362/992cda31-1753-4038-8678-fafdcd2397ee)

The user xpanse-admin-2 and user xpanse-admin has same name 'xpanse admin', when I login in with 'xpanse-admin-2', I can query the data of the user  'xpanse-admin', we should use the unique value of field 'preferred_username' or 'sub' to  distinguish users
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/0879c29c-6acb-4df2-a762-a05f5c2852d1)

In the Zitadel, user can modify the 'preferred_username', so we must use 'sub' as id to fill 'userName' and 'xpanseUser' in calling APIs.
![chrome_yJblEpFnDh](https://github.com/eclipse-xpanse/xpanse/assets/121531362/bf918689-de93-427c-b7d6-51ac8e2b2c17)

**Comment by swaroopar** [comment]
@baixinsui yes, you are right. We must use the 'sub' field in the token to get the unique ID. 
We must handle this as part of the #623 user story where we want to remove the 'xpanse username' field everywhere. 
I will add this point there as well.  It should be good to store only Id in our DB too. This is more secure as this would us from storing any user related information in DB. 

and as part of the same userstory (or we can split), UI will not send any username any more in the request.

**Comment by Alice1319** [comment]
I'll take it

**Comment by baixinsui** [comment]
This is based on #623, I will take it for debugging between UI and API.
