### ISSUE TITLE
wrong documentation of mandatory field

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#649]
In the  `getAvailableServicesTree` method, the category field is documented as optional. But this is wrong. Even OpenAPI ignores this config. All path variables are by default only mandatory. 

We must remove this config to maintain uniformity. 

https://github.com/eclipse-xpanse/xpanse/blob/df42f452bdb54190c65d7614c10faef4abcc368b/modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java#L239

**Comment by jinyangyang222** [comment]
I will fix it.
