### ISSUE TITLE
Split catalog API methods to ServiceCatalogApi

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#654]
Currently service catalog API methods are part of [ServiceDeployerApi](https://github.com/eclipse-xpanse/xpanse/blob/468fc585d8c027dd73a08d946f836e2a0d29e727/modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java#L68).

- [ ] Create new class `ServiceCatalogApi`
- [ ] Move all methods with tag "Services Available" to the new class

**Comment by jinyangyang222** [comment]
I will take it.
