### ISSUE TITLE
Add credential - variables form does not update when different "name" is chosen

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#658]
When a CSP adds multiple credential definitions of same credential type "Variables" but with different "name", then the form does not update the variables list when user changes the "name" from drop-down.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/25f9cb2f-f1bd-4c77-92ed-10890c459b90)

**Comment by swaroopar** [comment]
@WangLiNaruto can you please look into this?

**Comment by WangLiNaruto** [comment]
> @WangLiNaruto can you please look into this?

@swaroopar sure,I will fix it

**Comment by WangLiNaruto** [comment]
@swaroopar  sure,I will fix it
