### ISSUE TITLE
handle adding multiple credentials

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#661]
Currently when multiple credentials are added after opening the 'add credential' modal, the 'success' message of the previously added credential remains as it is. 

After the credential is added successfully

- [ ] Disable the 'Add' button in the modal
- [ ] When user changes anything in the Csp, Type or Name dropdown, remove the previous success message, enable the Add button again. 

Additionally also keep the 'Name' field always displayed just like the 'Type' field. Only keep it with empty value and disabled. Enable it after 'Type' is selected.

**Comment by WangLiNaruto** [comment]
I will fix it
