### ISSUE TITLE
ServiceCatalogApi-  getAvailableServicesTree mothod，The "links" attribute in the returned result is empty

### ISSUE THREAD

**Issue by jinyangyang222** [eclipse-xpanse/xpanse#662]
"links" has a value in the result returned by the listAvailableService method, but getAvailableServicesTree  does not

[
![07261](https://github.com/eclipse-xpanse/xpanse/assets/121534745/963fe3f0-8053-49f6-b107-4d70b1ad78b8)
](url)
[
![07262](https://github.com/eclipse-xpanse/xpanse/assets/121534745/b53064a5-4bc9-4a14-b7ef-0ae54856cf61)
](url)

**Comment by jinyangyang222** [comment]
@swaroopar @baixinsui  Do we need to set values for 'links' uniformly here?

**Comment by swaroopar** [comment]
@jinyangyang222 yes, we will have to keep it uniform.

**Comment by jinyangyang222** [comment]
I will fix it.
