### ISSUE TITLE
ServiceCatalogApi-  availableServiceDetails method, When the incoming ID is incorrect, an empty object is returned;

### ISSUE THREAD

**Issue by jinyangyang222** [eclipse-xpanse/xpanse#665]
When the incoming ID is incorrect, an empty object is returned, like this.
[
![072701](https://github.com/eclipse-xpanse/xpanse/assets/121534745/25ae1a3b-e43e-438a-961e-4177d3bf8110)
](url)

Should ServiceNotRegisteredException be thrown at the database layer when the incoming id is incorrect,like this.
[
![072702](https://github.com/eclipse-xpanse/xpanse/assets/121534745/d754ab98-093d-47e6-890d-e394f975a0ec)
](url)

**Comment by jinyangyang222** [comment]
@swaroopar Hi swaroopar,Do we need to fix it here?

**Comment by swaroopar** [comment]
@jinyangyang222 yes, you are right, we need such a valid exception with HTTP 400. 
This must be fixed.

**Comment by jinyangyang222** [comment]
> @jinyangyang222 yes, you are right, we need such a valid exception with HTTP 400. This must be fixed.

ok,I will fix it.
