### ISSUE TITLE
Csp  Category-- Throw an exception for unsupported values during serialization

### ISSUE THREAD

**Issue by jinyangyang222** [eclipse-xpanse/xpanse#667]
Csp -- Define new exception "UnsupportedCspException" 
Category --  Define new exception "UnsupportedCategoryException" 

In the current Csp and Category classes, if the passed in value is not supported, serialization will return null.
Throw this exception during serialization when an unsupported value is passed in.

**Comment by iskey** [comment]
maybe a generic exception for enumerate is a better choice.

**Comment by jinyangyang222** [comment]
> maybe a generic exception for enumerate is a better choice.

ok, I will fix it.
