### ISSUE TITLE
Respond to HTTP 200 when non mandatory parameters are passed in with incorrect values

### ISSUE THREAD

**Issue by jinyangyang222** [eclipse-xpanse/xpanse#668]
[
![072703](https://github.com/eclipse-xpanse/xpanse/assets/121534745/e0567393-d3c3-4673-831e-3a1e983f5cb0)
](url)

For non mandatory parameters such as' serviceVersion ', when incorrect values are passed in, the response will still be HTTP 200.
Do we need to modify it to throw ServiceNotRegisteredException?

**Comment by swaroopar** [comment]
@jinyangyang222 in this case, empty list is fine. 
In case of mandatory parameters, when wrong values are sent, do we return empty list or exception?

**Comment by jinyangyang222** [comment]
> @jinyangyang222 in this case, empty list is fine. In case of mandatory parameters, when wrong values are sent, do we return empty list or exception?

ok, For mandatory parameters, currently an exception is returned
