### ISSUE TITLE
credentials in deployed variables are masked

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#676]
Deployment is using wrong method to fetch credentials. This is loading masked sensitive variables. 

[org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java:150](https://github.com/eclipse-xpanse/xpanse/blob/ad65e6de5a1e77d42fb13652a2d93f5055a9932b/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java#L150)

the correct method would be this https://github.com/eclipse-xpanse/xpanse/blob/ad65e6de5a1e77d42fb13652a2d93f5055a9932b/modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java#L231 which loads the variables from all sources.

**Comment by jinyangyang222** [comment]
I will fix it.
