### ISSUE TITLE
provide an option to run swagger UI with custom server URL

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#678]
Currently the Xpanse's server URL runs only with the default localhost URL. 
We need to add a configuration to allow custom URLs when the application is hosted anywhere else. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/230de341-a708-4459-a4f0-05156ed13c85)

**Comment by jinyangyang222** [comment]
I will do this.

**Comment by swaroopar** [comment]
@jinyangyang222 just an FYI.. after adding correct HTTP headers from LB.. the URL is updated. but it always shows HTTP.. It must be HTTPS in this specific case. Can you please see how springdoc handles this?

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/c7670fa0-a45f-435a-ba30-78fd4be3cc7a)

**Comment by swaroopar** [comment]
@jinyangyang222 i was able to get this working by adding correct headers on the load balancer. I would say we can close this. 
Sorry for the confusion.

**Comment by jinyangyang222** [comment]
> @jinyangyang222 i was able to get this working by adding correct headers on the load balancer. I would say we can close this. Sorry for the confusion.

Okay, that's okay. Let's close this one then

**Comment by swaroopar** [comment]
@jinyangyang222 sure. Let me keep this with me until i document what is exactly needed.
