### ISSUE TITLE
API returns HTTP 403 even when no authentication header is not passed

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#679]
When authentication header is not passed or if it is invalid, we must return HTTP 401 unauthenticated. 
Only when the RBAC check fails, we must return HTTP 403 unauthorized.

**Comment by swaroopar** [comment]
@baixinsui can you please check this? Would be nice to have this corrected before the demo tomorrow.

**Comment by baixinsui** [comment]
I haven't encountered the problem that API returns HTTP 403 even when no authentication header is not passed.

**Comment by swaroopar** [comment]
@baixinsui simply open the API URL in the browser. for example http://localhost:8080/xpanse/health 

or try any API method in the swagger UI without authenticating the user.

**Comment by baixinsui** [comment]
Ok. I will fix it.
