### ISSUE TITLE
flavor list values not updated based on cloud provider

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#691]
When a service is created with two cloud providers and when the flavor names are different,  the drop down does not recognize this. 
It always shows the drop down list from the first cloud service provider. 
This behavior is same on the migrate page also. Both must be fixed.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/5f4aa22a-5f3e-4140-a297-c7a3d6274d63)

**Comment by Alice1319** [comment]
I'll take this
