### ISSUE TITLE
UI- Credentials List user show blank 

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#693]
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/02f70d20-1e9f-4010-b64b-f3a2d8090b91)

Remove the field user.

**Comment by baixinsui** [comment]
I will take it.

**Comment by swaroopar** [comment]
@baixinsui i think we can remove this column itself. It is not relevant anymore.
