### ISSUE TITLE
UI - Actions 'migrate' and 'destroy' of deployed service should be retained when the ServiceState is 'DESTROY_FAILED' 

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#695]
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/b19d9324-434d-48de-931d-00eaddf77d64)
If the ServiceState of DeployedSerice is 'DESTROY_FAILED' , the actions 'migrate' and 'destroy' should be retained.

**Comment by WangLiNaruto** [comment]
let me do it
