### ISSUE TITLE
When manage service templates validate csp-user whether has same metadata value of key 'manage-csp'.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#698]
~~Solution 1:~~
~~- [ ] Add String field 'userId'  in the DB entity 'RegisterServiceEntity' to record the csp-user who registered the template;~~
~~- [ ] Validate current login user id of the csp-users when update or unregister the registered service template;~~
~~- [ ] If current login user own role 'admin', need not to validate the user id.~~
~~- [ ] Csp-users can list all registered service templates , but only can modify those registered by can only modify themselves.~~
~~- [ ] Add boolean field 'hasModifAuthority' in the view object 'RegisteredServiceVo', if false, on the UI page disable buttons 'update' and 'unregister'.~~

~~Solution 2:~~
~~- [ ] Add roles like 'csp-x' for all values in Enum Csp such as 'csp-huawei','csp-aws' etc.~~
~~- [ ] In all methods to register\update\unregister service template, if the current login user doesn't have the role 'csp-x' and the 'x' is not same as the name of Csp in the service template, return 403 'Access Denied'.~~

Solution 3:
- [ ] Add metadata for csp-user who manage service provider  like 'huawei' with key 'manage-csp' or other key and value 'huawei';
- [ ] Add scope 'urn:zitadel:iam:user:metadata'  into Scopes of OAuth2 Flow both apps Xpanse-API and Xpanse-UI;
- [ ] Filter the value of key 'urn:zitadel:iam:user:metadata' in authorized claims and put it into field 'metadata' of object CurrentUserInfo in the app Xpanse-API;
- [ ] Validate the value of key 'manage-csp' in field 'metadata' of  object CurrentUserInfo is whether same as the  value of field 'namespace' in the related object such as 'CreateServiceTemplate' ,  'ServiceTemplateEntity' etc.

**Comment by baixinsui** [comment]
@swaroopar @iskey Do you have other good idea for this?

**Comment by swaroopar** [comment]
@baixinsui I had this point on my list too. In my opinion, we will have multiple csp roles, example - csp-k8s-admin, csp-kafka-admin. All users belonging to a specific CSP group must be allowed to register,update and delete.

**Comment by swaroopar** [comment]
@baixinsui apologies. my example names were not very clear. What I meant is.. using xpanse any software vendor can offer his software as a managed service.
So for example.. if a csp/company named X  wants to offer services such k8s, Kafka, mongoDB on different cloud providers.. then the role will be csp-x.
And users with this role will have access to all. Service templates offered by company X.

**Comment by baixinsui** [comment]
Ok，I understood. Does admin-user have permission to modify all service templates of all Csp?

**Comment by swaroopar** [comment]
@baixinsui 

1. Listing service templates must be limited to that specific csp. 
2. Admin can have read only rights. If necessary, for now we can simply do not provide any access to admin users via the standard APIs.

**Comment by baixinsui** [comment]
@swaroopar @iskey Based on today's discussion with you, I have updated the Issue. Could you please help me see if there are any other comments.
Except the item list in this issue,
 I think we should add a module to create csp-users for the xpanse admin user , in the new module we can use the APIs of the IAM service to  create user and grant role 'csp' to new user and add metadata for new user. This ensures that the key of metadata we fill in is fixed and the value is from the available CSP enum we defined.
 At present, we have implemented the granting the default role 'user' to the login user without any roles, so the end-users can directly use the xpanse service through registration after opening the registration function on the IAM service.
 If there only can be one admin user for the Xpanse system, we can initialize the only xpanse admin user through the terraform script in the Xpanse-iam project. else the admin users can be more than one, we can add a module to create admin-users for the xpanse admin user
Of course, we can complete these with a new issue in the future sprint.

**Comment by swaroopar** [comment]
@baixinsui the issue description looks good. 
Regarding user and role management, we will keep this for the future. For now, it is enough for us to document how user management is currently done.

we can open a new issue for documenting this. We must add it to the doc website.

**Comment by swaroopar** [comment]
documentation updated - https://eclipse.dev/xpanse/docs/authentication-authorization#oidc-metadata
