### ISSUE TITLE
When no service is available, the monitoring query sends a null pointer

### ISSUE THREAD

**Issue by Alice1319** [eclipse-xpanse/xpanse#703]
![image](https://github.com/eclipse-xpanse/xpanse/assets/42802200/36678ce2-8b3b-4da0-ac99-83959b5d9772)

![image](https://github.com/eclipse-xpanse/xpanse/assets/42802200/e39608b5-2f77-44f2-8e7d-8486df6d98b2)

**Comment by jinyangyang222** [comment]
I will fix it.
