### ISSUE TITLE
UI Monitor Page Automatic call API '/services/deployed' too frequently to get Response When Oauth is enabled

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#704]
![msedge_rsntFmYlRx](https://github.com/eclipse-xpanse/xpanse/assets/121531362/2521bbea-4377-47de-910c-d6879b9e8789)
Call the Api one time peer second but response need more than one second.

Or we can add button 'monitor' in list of myDeployedService, like 'detail', 'migrate'..
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/7883e44c-ab12-477a-94fb-e7a923aad620)

**Comment by swaroopar** [comment]
@baixinsui @Alice1319 We have to check if the same issue is happening in the branch where JinPing is refactoring monitoring. 

It is also good idea to keep monitoring inside "MyServices". That is how it is in other cloud provider consoles. Let us discuss this and plan this for next sprint.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by Alice1319** [comment]
> @baixinsui @Alice1319 We have to check if the same issue is happening in the branch where JinPing is refactoring monitoring.
> 
> It is also good idea to keep monitoring inside "MyServices". That is how it is in other cloud provider consoles. Let us discuss this and plan this for next sprint.

The latest code does not have this problem.
