### ISSUE TITLE
Remove dependency on openapi-generator-cli-version.jar

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#705]
Currently, we download the  `openapi-generator-cli` jar during the runtime if it is done found or in case of docker image, we build an image by copying the jar into it. We must remove this dependency so that we can build a plain java docker image. 

- [ ] As part of the maven build, add a step that downloads the jar file to resources folder. Eg., https://stackoverflow.com/questions/2741806/maven-downloading-files-from-url
- [ ] At the runtime, the file is only read from the `resources` directly and copied outside the jar if the file does not exist. 
- [ ] If this works, remove the dependency in the docker file too.

**Comment by jinyangyang222** [comment]
let me try do it.

**Comment by jinyangyang222** [comment]
@swaroopar  Hi swaroopra,I use the Maven plugin to download openapi-generator cli.jar to the target directory and use it directly. It works on Windows, but I cannot find openapi-generator cli.jar in the target directory on Linux. 
I checked that the file path is OK, but after starting Xpanse through the jar package, I couldn't find the openapi-generator cli.jar in the target directory. baixinsui also encountered this problem, it cannot work.

**Comment by swaroopar** [comment]
@jinyangyang222 oh ok. which plugin did you use?

**Comment by jinyangyang222** [comment]
> @jinyangyang222 oh ok. which plugin did you use?

<maven-dependency-plugin>

**Comment by jinyangyang222** [comment]
> @jinyangyang222 oh ok. which plugin did you use?

@swaroopar  <maven-dependency-plugin>
