### ISSUE TITLE
terraform-boot - Enable conditional oauth authentication

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#714]
Since terraform-boot is a generic solution to run terraform command behind a REST API, we must implement authentication which can only be conditionally enabled. By default no authentication is necessary. 

1. Add spring-security (similar to xpanse APIs) to terraform-boot api and swagger-ui
2. Add documentation on how to enable it and what properties must be passed if enabled. 
3. Add configuration to Zitadel terraform scripts to ensure this new API client is also added to the Oauth provider.

**Comment by jinyangyang222** [comment]
I'll take this.

**Comment by baixinsui** [comment]
@swaroopar I think it's unnecessary to create new API client and Swagger-UI Agent for terraform-boot anymore. We can directly use the applications configuration of the xpanse API.

**Comment by swaroopar** [comment]
@baixinsui yes, we can reuse the configuration from existing applications for now. But the namings will get mixed up. 
Should we consider renaming the "xpanse-api" application to just "api"?
We must also add the redirect url for spring boot swagger ui.

**Comment by baixinsui** [comment]
@swaroopar Yes, the redirect url is necessary. @jinyangyang222  The task 3 can be implemented according to the above discussion.

**Comment by jinyangyang222** [comment]
@baixinsui @swaroopar okay.
