### ISSUE TITLE
terraform-boot - provide docker file

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#716]
We must deliver terraform-boot as docker image.

- [ ]  Add a Dockerfile for the spring-boot app with terraform installed. We can refer to these files  as examples

 https://github.com/naorlivne/terraformize/blob/master/Dockerfile-arm
 https://github.com/eclipse-xpanse/xpanse/blob/main/Dockerfile

**Comment by jinyangyang222** [comment]
I will take it
