### ISSUE TITLE
UI - service migration - fully broken

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#725]
service migration feature on the UI is not working at all.

1. all `serviceRequestProperties` sent in the deploy request is always null. 
05:23:14.057 [http-nio-8080-exec-3] INFO  o.e.x.m.logging.CustomHttpLogWriter [204b3f36-e82d-41eb-97ad-939991bc18e6]- Request: POST /xpanse/services/deploy  {"category":"compute","csp":"openstack","flavor":"Ubuntu 22.04 8GB RAM","region":"RegionOne","serviceName":"vm-scs","version":"v2.50.16","customerServiceName":"vm-test-2","serviceRequestProperties":{"vm_name":null,"network_name":null}}

2. Destroy request is triggered even when the new service deployment fails.
3. Status fetching triggers a wrong request initially  and we can see the below long on server. 
405:23:12.782 [http-nio-8080-exec-8] DEBUG o.s.s.w.f.HttpStatusRequestRejectedHandler [322a9359-b8e1-41d1-858a-5792cb375f8b]- Rejecting request due to: The request was rejected because the URL contained a potentially malicious String "//"
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:535)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:505)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/75db3ffe-6aff-4a85-b881-5906e7f9cc0a)

4. Please also validate that no warnings are logged in the console logs.

**Comment by Alice1319** [comment]
I'll fix it
