### ISSUE TITLE
UI  - credentials page error not clear on successful reload

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#728]
If the loading of credentials initially fails, there is an alert displayed. 
But this alert remains even when the consecutive requests are successful. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/6a56c1ef-a7cf-4bed-a176-9e818f50fdc8)

**Comment by WangLiNaruto** [comment]
let me do it
