### ISSUE TITLE
UI-Query available services using method 'listAvailableServices' instead of 'getAvailableServicesTree'.

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#732]
According to issue https://github.com/eclipse-xpanse/xpanse/issues/660, we plan to remove the method 'getAvailableServicesTree' in the ServiceCatalogApi, Before refactoring Catalog API related https://github.com/eclipse-xpanse/xpanse/issues/721, we must use method named 'listAvailableServices' to replace method named 'getAvailableServicesTree'  and group the result list in the UI client.

**Comment by Alice1319** [comment]
I'll take this
