### ISSUE TITLE
disable jacoco by default. Enable only in CI pipeline

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#740]
Currently jacoco plugin runs always when maven build is executed. This is not necessary. 

- [ ] Introduce a flag to disable the test coverage by default. 
- [ ] Enable this only in the ci pipeline here https://github.com/eclipse-xpanse/xpanse/blob/main/.github/workflows/coverage.yml#L27

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by jinyangyang222** [comment]
I will take it.
