### ISSUE TITLE
compile terraform-boot API

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#757]
- [ ] add a new package under "org.eclipse.xpanse.modules.deployment.deployers.terraform" with name "terraformboot"
- [ ] Copy the openapi json file from terraform-boot API under resources folder of "deployment" folder. 
- [ ] Add the openapi-generator maven plugin  which reads this JSON and generates the API client and model. (similar to what we do on  UI to generate the client and models for xpanse API)
- [ ] the maven plugin must be only executed on demand. It must be disabled by default. 
- [ ] Document how to run the plugin and generate the client again.
- [ ] Commit the API JSON, data models and client to GitHub

**Comment by jinyangyang222** [comment]
@swaroopar Hi Swaroopar,If we follow this approach, does it mean that we need to use the client method to call the terraformboot API? Usually, we use HTTP calls, so is there any other consideration for doing so?

**Comment by swaroopar** [comment]
@jinyangyang222 I would prefer to use the client also which is auto generated. During the generation, you can also mention which type of http Client you need.. for example RestTemplate.
