### ISSUE TITLE
add CSP logo to the registration view

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#765]
currently the registration view only displays the name of the CSP. We must change this to the logo of CSP so that the UI is consistent everywhere. 

same must be done on the on the 'update' UI also.

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/ba45fc7c-2b55-461a-a74a-c479454c5c1f)

**Comment by Alice1319** [comment]
I'll take this.
