### ISSUE TITLE
Destroy service broken on openstack

### ISSUE THREAD

**Issue by Alice1319** [eclipse-xpanse/xpanse#769]
![image](https://github.com/eclipse-xpanse/xpanse/assets/42802200/5efbd9af-2c56-4532-b0e3-d2d10c2297bd)

![image](https://github.com/eclipse-xpanse/xpanse/assets/42802200/4130c700-d01f-4127-9606-1c9b19e2ab80)

**Comment by baixinsui** [comment]
I will fix it.
