### ISSUE TITLE
add copy-to-clipboard option to all service details

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#777]
- [ ] create a common component which implements copy to clipboard in xpanse-ui. We can consider using - https://github.com/nkbt/react-copy-to-clipboard
- [ ] The copy to clip board icon must be displayed at the following places
1. on each element in the service details list on the service successfully deployed alert in the MyServices -> Details page.
2. On the 'service id' field in the order successful and order failed screens. 
3. On registration successful alert -> the service UUID must have this.

**Comment by Alice1319** [comment]
I'll take this
