### ISSUE TITLE
store order form data until order is submitted

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#779]
Currently the order form data is lost if we switch tabs during ordering process. 

- [ ] use `zustand` library for storing form data. 
- [ ] when the user goes back using the 'back' button and comes again to the form, all previous entered data must be displayed. 
- [ ] if the user goes back and changes version -> we must still try to reuse the values for all fields which have same names.
- [ ] Same logic must also be added in the migrate screen.

**Comment by Alice1319** [comment]
I'll take this
