### ISSUE TITLE
add API method to get credentials openapi link

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#780]
- [ ] Similar to service catalog method [OpenApiMethod](https://github.com/eclipse-xpanse/xpanse/blob/70a22f1ca4dd7970cc59bc5e11277f969d33a9ea/modules/api/src/main/java/org/eclipse/xpanse/api/ServiceCatalogApi.java#L133), implement in credentialsApi for the OpenAPI documents generated for credential configurations. 
- [ ] the URI must contain Csp and Credential Type as parameters.

**Comment by jinyangyang222** [comment]
I'll take it.

**Comment by jinyangyang222** [comment]
This already exists, CredentialManageApi - Line 154.

**Comment by swaroopar** [comment]
@jinyangyang222 thank you for checking this. My fault. I was looking at the wrong place.
