### ISSUE TITLE
reduce size of xpanse docker image

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#781]
-currently the terraform-boot docker image uses the eclipse-temurin:17 image which is too big.

- [ ]  Change this to use the alpine and also only the "jre" installed base images.
- [ ] Remove the fixed aes_sec file in the image and instead create the private key at the start of the container. https://stackoverflow.com/questions/42857897/execute-a-script-before-cmd
- [ ] Remove references of maven `jib` plugin in the POM xmls. This is not used anymore.

**Comment by jinyangyang222** [comment]
I'll take this.
