### ISSUE TITLE
show credentials openapi documentation in add/update credentials UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#782]
similar to order catalog UI, the credentials openapi documentation link must be displayed in the UI. 

the API method here https://github.com/eclipse-xpanse/xpanse/blob/0d54b787e4637904564b15b5ec44435c13d80fc9/modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java#L154 must be called to get the link .

**Comment by WangLiNaruto** [comment]
let me do it
