### ISSUE TITLE
Mask all end point details

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#784]
For all end point details, we must ask the key values and provide an option to unmask for each of the fields.

We need the same functionality in myServices -> Details button and also in the deployment successful alert. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/5b5db244-3aea-4bbf-a6a6-c3b1017e381e)

**Comment by Alice1319** [comment]
I'll take this
