### ISSUE TITLE
perform rollback when deployment fails

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#787]
As part of terraform apply, if any steps fails after some resources are created, then terraform does not do a automatic rollback. 

- [ ] After the deployment fails in between due to a error from Terraform plan/apply, store the already provisioned resources like we do in case of success cases https://github.com/eclipse-xpanse/xpanse/blob/27a366f138933b7395eee293c7950e9c049881e4/modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java#L196
- [ ] if any resources were already provisioned, execute a destroy immediately. . 
- [ ] Ensure the deployment failure message is correctly stored and not overwritten by destroy messages. 
- [ ] If the Destroy fails set the service to a new status MANUAL_CLEANUP_REQUIRED.
- [ ] service state remains as DEPLOY_FAILED if the destroy is successful.

**Comment by jinyangyang222** [comment]
I‘ll take this.
