### ISSUE TITLE
implement new purge API method

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#788]
- [ ] Add new purge API method. 
- [ ] This method can run only if service status is DEPLOY_FAILED or DESTROY_FAILED or MANUAL_CLEANUP_REQUIRED
- [ ] Service runs destroy of the method if any resources are available in the deployResources. 
- [ ] Ignore errors from destroy, if any and delete the DB entry at the end.

**Comment by jinyangyang222** [comment]
I'll take this.
