### ISSUE TITLE
Add `namespace` to the xpanse user with the role `CSP`

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#792]
We want to add the namespace property to the xpanse users with the role `CSP`.
As we are using Zitadel to manage our users, the meta field may be a good choice, let's have a try.

- [ ] Add namespace property to the meta of the users with the role `CSP`
- [ ] Turn this property to `namespace` at the API level of the xpanse.

**Comment by baixinsui** [comment]
I will take this.
