### ISSUE TITLE
Add `JWT` support to Xpanse's authentification 

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#793]
Regarding the API authentication for Xpanse, they currently call Zitadel's API to validate the user's token each time. This approach might potentially strain Zitadel's capacity in the future. To mitigate this, we should contemplate integrating JWT for Xpanse to independently verify tokens.

- [ ] Integrate JWT support at the Xpanse API level.
- [ ] Incorporate configurations into Xpanse for switching between JWT and traditional ways.

**Comment by baixinsui** [comment]
I will take it.
