### ISSUE TITLE
Metrics for HuaweiCloud need to be updated

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#800]
# Metrics for HuaweiCloud need to be updated

![image](https://github.com/eclipse-xpanse/xpanse/assets/1907997/b2129508-1165-4fa6-84b2-7e71a47ffb2e)

![image](https://github.com/eclipse-xpanse/xpanse/assets/1907997/46a3b79d-45f4-4cf2-b670-1752012fef8a)

**Comment by Alice1319** [comment]
I‘ll take this

**Comment by jinyangyang222** [comment]
I'll fix this
