### ISSUE TITLE
Register Panel doesn't respond to clicking after one process of registering

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#801]
# Register Panel doesn't respond to clicking after one process of registering

![image](https://github.com/eclipse-xpanse/xpanse/assets/1907997/675cac23-af0d-47e8-905c-96d01f1f4124)

**Comment by Alice1319** [comment]
I'll take this

**Comment by swaroopar** [comment]
@iskey @Alice1319 we must once discuss what should be the expected behaviour?
In the current implementation, we must earlier delete the uploaded file or click on try again to start a new registration.

**Comment by iskey** [comment]
@swaroopar , click on try again is ok on this page, But it does not respond the clicking even when the registering is successful.

**Comment by swaroopar** [comment]
@iskey you mean, deleting the file does not work in case of successful registration?
![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/b5d8a315-4413-49a2-9cd6-b6ae1ae579f3)

**Comment by iskey** [comment]
I mean the `Register Panel` on the left side, Is it designed like this?

**Comment by swaroopar** [comment]
@iskey yes, that is how it is currently. the page does not refresh when you click on register panel option again. This is same for all other menu options also. 

May be in case of successful registration, we must provide an option 'register another service'? similar to 'try again' in case of failure?

**Comment by iskey** [comment]
Ok thank you @swaroopar, I think making the menu button responsive again is a good option. Anyway, I will close this issue for now.
