### ISSUE TITLE
UI - form cache behavior very sporadic

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#806]
currently the form cache implemented using Zustand has the following issues. 

1. Only last entered form field is stored. 
2. sometimes the last character is not stored. 
3. Default values are stored. We must store only user entered values.

**Comment by swaroopar** [comment]
a solution for new order deployment is implemented in https://github.com/eclipse-xpanse/xpanse-ui/pull/175
The same needs to be tested and extended for migration use case as well.

**Comment by Alice1319** [comment]
I'll check it
