### ISSUE TITLE
add purge option to my services

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#816]
In case of "Deployment failed" and "Destroy Successful" jobs, we must add "purge" option to myServices. 

1. Replace the "destroy" button with "purge" button in case of these two states only.
2. On click of "purge", show a message  for user confirmation -> default must be "no". 
3. On click on "yes" -> call the purge method and poll responses -> all logic similar to "destroy" button. 
4. when the service `getServiceDetailsById` returns 404 -> means the service is purged and we can refresh the table. 

Note - additionally, please also change the destroy and migration user confirmation to have default has "no".

**Comment by Alice1319** [comment]
I'll take this
