### ISSUE TITLE
update URLs for register page based on request state

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#824]
- [ ] On failure of registration - update url to "register/failed"
- [ ] If yaml invalid - update url to "/register/invalid
- [ ] On successful registration - update url to "/register/successful?id=${service_id}"
- [ ] on click of "try again" -> get the url back to "/register"
- [ ] In case, logout is performed on any of these new URLs, the login must be re-directed to "/register" url. Logic must be added here - https://github.com/eclipse-xpanse/xpanse-ui/blob/main/src/components/content/login/Logout.tsx#L14
- [ ] when we refresh the page with the new URLs or directly open this URL.. we must redirect to "/register" page which is for registering a new service.

**Comment by Alice1319** [comment]
I'll take this
