### ISSUE TITLE
Remove invalid CSP options from the credential center

### ISSUE THREAD

**Issue by iskey** [eclipse-xpanse/xpanse#830]
- [ ] Remove CSP items which are not in the pluginsMap

![image](https://github.com/eclipse-xpanse/xpanse/assets/1907997/73debc5f-451f-42ed-825b-d4e255742ea4)

**Comment by swaroopar** [comment]
@iskey how about providing a new API method which returns a list of CSPs which have a plugin active? Otherwise I don't see any other straight forward way for the client to know which CSPs have an active plugin.

**Comment by baixinsui** [comment]
I will do it by adding a new API.

**Comment by iskey** [comment]
> @iskey how about providing a new API method which returns a list of CSPs which have a plugin active? Otherwise I don't see any other straight forward way for the client to know which CSPs have an active plugin.

@swaroopar , yes, How about adding a new API named `/xpanse/csps?active=true` grouped under the `admin`?

**Comment by swaroopar** [comment]
> > @iskey how about providing a new API method which returns a list of CSPs which have a plugin active? Otherwise I don't see any other straight forward way for the client to know which CSPs have an active plugin.
> 
> @swaroopar , yes, How about adding a new API named `/xpanse/csps?active=true` grouped under the `admin`?

@iskey yes that's a good idea.
