### ISSUE TITLE
Test xpanse full stack with docker images

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#836]
Now since we have most of the terraform-boot related changes implemented, it is necessary once do an end to end testing of full set of xpanse docker images. 

- [ ] Use the latest docker images which were created for xpanse, xpanse-ui and terraform-boot. -> https://github.com/orgs/eclipse-xpanse/packages
- [ ] Check if registration, deployment works.
- [ ] Document changes required in the current documentation - https://eclipse.dev/xpanse/docs/runtime/

**Comment by WangLiNaruto** [comment]
let me do it
