### ISSUE TITLE
remove unused enum values from ResultType

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#839]
We had copied all the enums values from xpanse to terraform-boot. Pls keep only that is valid for terraform-boot.
https://github.com/eclipse-xpanse/terraform-boot/blob/3dd72ac30564eb201faf5846fe64dbd8c62f6d97/src/main/java/org/eclipse/xpanse/terraform/boot/models/response/ResultType.java#L16

**Comment by WangLiNaruto** [comment]
let me do it
