### ISSUE TITLE
update property name terraform-boot.endpoint

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#841]
The current property name is not uniform. 
https://github.com/eclipse-xpanse/xpanse/blob/668cdbe2bc7fba0f83be4be2875c17f7dd7d2551/runtime/src/main/resources/application-terraform-boot.properties#L10

Make it `terraform.boot.endpoint` and update docs if necessary.

**Comment by jinyangyang222** [comment]
I'll fix it.
