### ISSUE TITLE
update resttemplate logging format using interceptor

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#844]
Currently the rest template is using the default logging which is not optimal and does not match to our other log lines. Instead we must provide a custom log interceptor.

- [ ] Add a custom log interceptor for both terraform boot and flexible engine Rest template. The log lines must look similar to how we log our own HTTP request and response. Just one line for request, one for response. 
Example - https://objectpartners.com/2018/03/01/log-your-resttemplate-request-and-response-without-destroying-the-body/
- [ ] Remove this existing config https://github.com/eclipse-xpanse/xpanse/blob/668cdbe2bc7fba0f83be4be2875c17f7dd7d2551/runtime/src/main/resources/application.properties#L24
- [ ] Log request and response details with 'info' level. 
- [ ] Ensure no logging is done by the 'RestTemplate' package. We log only from our interceptor classes. 
- [ ] We can also define one interceptor and use it in both terraform-boot and flexible engine client.

**Comment by WangLiNaruto** [comment]
let  me do it

**Comment by jinyangyang222** [comment]
I'll take it.
