### ISSUE TITLE
webhook - terraform output and deployed resources info not parsed

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#859]
From the webhook request, the terraform output and resources not parsed. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/bfc4e27e-98b6-463c-b726-d1e36ec0550d)

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/cf0bc161-88a7-44bf-afd3-4c198562498e)

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/29841515-b16c-4ba9-b79c-89009d7c3a0a)

**Comment by WangLiNaruto** [comment]
let  me do it
