### ISSUE TITLE
fix myservices scroll for smaller screens

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#860]
Buttons on myservices page are misplaced on smaller screens (whenever a horizontal scroll is active)

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/267749f6-e121-401d-a467-c914c01bbcf7)

**Comment by Alice1319** [comment]
I‘ll take this

**Comment by swaroopar** [comment]
done.
