### ISSUE TITLE
end point details not fully displayed on unmask

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#864]
End point details on the deployment status alert is masked but when unmasked, the value is not fully displayed. The user has to scroll through the value. 
This must be changed to display full value directly. This works fine in the 'details' modal of 'MyServices' page. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/e53b8e17-4dec-43da-ad2b-21d1cf1fdb0d)

**Comment by WangLiNaruto** [comment]
let me do it
