### ISSUE TITLE
fix color of copy to clipboard icon

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#865]
Currently only copy to clipboard icon has a different color compared to other icons and text. 
This must be made the same grey color  like the 'unmask' icon. No need to highlight "copy" icon with special color. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/62fd6abd-d3be-4494-9874-94042f1ff4c4)

**Comment by WangLiNaruto** [comment]
let me do it
