### ISSUE TITLE
Update variable validator format to follow JSONSchema/openapi specifications

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#866]
Currently the validator for a deployment variable is configured as  pipe separated string which is not very straight forward. Also the `VariableValidator` is not exposed at all. 

https://github.com/eclipse-xpanse/xpanse/blob/ec910cd39b8c5fbcafa124e196bcb41b66b4e555/modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/DeployVariable.java#L52

- [ ] Make validator a map of <VariableValidator, String>.
- [ ] Rename `validator` field in `DeployVariable` to `valueSchema` and document the field as detail as possible.
- [ ] Make the `VariableValidator` enum have values same as the JSON values-> https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00 -> we can use the values in OpenApi schema object which is a superset of JSON schema but consider the next point. Validating the field will not be straightforward. 
- [ ] Consider using any existing JSON validation libraries for data validation instead of custom validation - https://github.com/networknt/json-schema-validator

P.S - Once this is implemented, we will also have the similar OpenApi validation on UI for the deploy variables.

**Comment by jinyangyang222** [comment]
I'll take this.
