### ISSUE TITLE
Prepare new demo video

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#867]
Based on the existing demo video, consider the following changes to the comments and add new screens mentioned. 
We can use the demo environment for preparing the video. 

**Note - we need the video to be prepared within this week as we plan to play in the next week's event.** 

	1. New show swagger API => https://demo.xpanse.site/swagger-ui/index.html => REST API methods offered by Xpanse. (just scroll through available services in swagger UI)
	2. Register deployment templates of services => Software Vendor's login to manage services that they plan to offer. 
	3. Register deployment templates of services => Register a new service using its service template
	4. View openAPI documentation for deploying service => View the OpenAPI document that can be used for deploying the service.
	5. Update  registered deployment templates of service => Update service template of an already registered service.
	6. Unregister registered deployment templates of service => Remove already registered service templates from catalog. 
	7. End user login to manage service instances =>  End user's login to order manage services
	8. Deploy service templates and get service instances => Browse service catalog and order a service.
	9. MyService View => View details of a deployed service.
	10. Monitor View => View metric details of a deployed service. => go to monitor view from Myservices page
	11. Destroy deployed service instances => Destroy a deployed service.
	12. Migrate deployed services to other cloud service providers => migrate a deployed service to another cloud service provider. 
	13. New => Purge a service completely. 
	14. New => Add, update and delete cloud credentials.
	15.  Admin login => show healtcheck

Note - We must discuss the style of text on the video. Please discuss with @swaroopar and/or @iskey to try different possibilities. 
Use English language on the system used for preparing demo.

**Comment by swaroopar** [comment]
@baixinsui for point 2 -> ok, I will change this. 
for point 3 -> yes we can do it. Just to highlight, we need the demo to be ready within this week, as we must play this in the event next week. In case, addition any new use-case to the demo takes more effort, pls let me know. We can discuss if we it is really needed for next week.

**Comment by baixinsui** [comment]
OK.

**Comment by baixinsui** [comment]
@swaroopar  I found a problem. When I logout with an isv-user and the login with a end-user, there will be a warining as below, but when I click the  button 'Go Back',  no change in the page. I think it is a bug.  Should we fix it. make the 'Go Back' can redirect to the default homepage address of the current user role?
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/7351b51f-21cc-423c-9f7e-ccacf5b173e5)

**Comment by swaroopar** [comment]
@baixinsui for me the 'Go Back' takes to the login page.. which is also not correct. I think it is better to change 'Go Back' to 'Home Page' as you suggested.
![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/50106657-158a-4387-a5bc-2fe65371cf7f)

**Comment by baixinsui** [comment]
@swaroopar  I add a new issue about it. https://github.com/eclipse-xpanse/xpanse/issues/868.

**Comment by iskey** [comment]
The demo is ready now.
