### ISSUE TITLE
change all authorization properties to dot separated

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#869]
to maintain uniformity, the following properties must be changed from dash separated to dot  separated. 

authorization-token-type=OpaqueToken
authorization-server-endpoint=http://localhost:8081
authorization-api-client-id=
authorization-api-client-secret=
authorization-swagger-ui-client-id=

- [ ] update properties file and code
- [ ] Update documentation in website

**Comment by WangLiNaruto** [comment]
let me do it
