### ISSUE TITLE
issues with service unregister

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#883]
- [ ] When the API returns error. The exception is not correctly parsed. We are only showing stand error message.
- [ ] When the user closes the error alert, the page remains in a broken state. -> we must put the page back to its original state as soon as the unregister fails.
- [ ] when unregister button is clicked - 'No' must be the default selection. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/7be4fc46-b662-4697-a2b1-5d7c771e4b96)
![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/7d49d97c-cf75-4324-a330-d09a95c123db)

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/dfcb3d98-8662-4ccf-9e0f-7ad5e4f2168d)

**Comment by Alice1319** [comment]
I'll take this
