### ISSUE TITLE
issues with migration final result display

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#886]
- [ ] We are passing destroy service details. But we must pass the newly deployed service details. Because of this, no final result is displayed. https://github.com/swaroopar/xpanse-ui/blob/51669b5029fefff7cb56e40896fc448ca0c6a663/src/components/content/order/migrate/MigrateServiceStatusPolling.tsx#L354
- [ ] Also the endpoint details are not displayed. It must displayed similar to new order.

**Comment by Alice1319** [comment]
I‘ll take this
