### ISSUE TITLE
implement new migrate service using terraform-local

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#887]
- [ ] Implement a new REST POST method `migrate`.
- [ ] URI to have the 'id' of the service to be migrated. (same as `destroy` service)
- [ ] Request body to have the `CreateRequest` object. (same as `deploy` service)
- [ ] Extend the Service DB entity to store the original ID of the service. We must use this later for deleting the original service.
- [ ] Return the ID of the new service. (Same as the  `deploy` service)
- [ ] Terraform-local -> start a async process, run deploy first and once deploy is successful, run the destroy. We must not have any code duplication. We must simply use the existing methods.

**Comment by WangLiNaruto** [comment]
let me do it

**Comment by iskey** [comment]
@swaroopar ，Hi Swaroop, actually the steps of the migration should be more flexible, so we can retry this migrate task in case it failed on some steps,

so we should create a new DB entity for the migration workflow which similar like this:

![image](https://github.com/eclipse-xpanse/xpanse/assets/1907997/204cd81a-2542-48f3-bf0c-c7aa185b5e59)

**Comment by swaroopar** [comment]
@iskey yes we can build an extensive Workflow for this but it does not match to what we discussed today morning. In this case, we need a more complex implementation.
