### ISSUE TITLE
Create new GoLang based  application - policy-man

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#896]
- [x] Create REST api  method  POST - 'healthcheck'.
- [x] Package name must include 'opa'
- [x] We need a very generic project. So no where 'xpanse' or 'osc'  related namings or concepts must be used. 
- [x] Refer to terraform-boot's healthcheck method to create data models.
- [x] OpenAPI spec definition must be auto generated. 
- [x] Document how to access the API, swagger, in readme.

**Comment by jinyangyang222** [comment]
I'll take it
