### ISSUE TITLE
Increase test coverage of xpanse

### ISSUE THREAD

**Issue by baixinsui** [eclipse-xpanse/xpanse#933]
- [ ] Exclude the policy-man generate client code from code coverage report.
- [ ] Add unit tests for  uncovered  classes.
- [ ] Add integration testing using TerraformBoot deployment with WireMock.

**Comment by baixinsui** [comment]
I will take it.

**Comment by swaroopar** [comment]
@baixinsui I think the first point is already taken care of - https://github.com/eclipse-xpanse/xpanse/blob/main/suppressions.xml#L8

**Comment by baixinsui** [comment]
Completed by the PR https://github.com/eclipse-xpanse/xpanse/pull/941
