### ISSUE TITLE
service catalog API must only return data that is necessary for ordering the service.

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#940]
currently we use the 'UserAvailableServiceVo' data type for both service template API and service catalog. but not all data must be returned in the service catalog API which is for end users. 

- [ ] UserAvailableServiceVo -> Rename to ServiceTemplateDetailVo
- [ ] Create new data model -> `UserOrderableServiceVo' -> should be same as the existing UserAvailableServiceVo but without namespace, deployment, createTime, lastModifiedTime, serviceRegistrationState, flavors -> must be without properties. 
- [ ] catalog API returns services only which are in state registered and updated only. 
- [ ] Test changes with the UI to see nothing breaks.

**Comment by swaroopar** [comment]
@baixinsui as discussed with Yichao.

**Comment by baixinsui** [comment]
Ok. I will take this.
