### ISSUE TITLE
Refactor Flavor data model

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#951]
The [Flavor](https://github.com/eclipse-xpanse/xpanse/blob/145070f719637cba655176f1f0fc701b28ae1c73/modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Flavor.java#L19) type is currently shared between service template and orderable services. This must be changed. 

- [ ] Remove `properties` field from Flavor type and use it in the `UserOrderableServiceVo` type. 
- [ ] Create a new type `FlavorWithProperties` - which extends the Flavor type and additionally has `properties` field. Use it in the `ServiceTemplateDetailVo` type. 
- [ ] Check and update UI.

**Comment by baixinsui** [comment]
I see and I will take it.
