### ISSUE TITLE
validate rego policies of an user before service deployment

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#956]
As part of the async deployment process, if the user has stored any rego policies, they must be validated using policy-man

1. Call the policy-man API method with the all the policies store for a respective CSP.
2. If the validation fails, define new exception type and return the failure as this exception.

**Comment by swaroopar** [comment]
@baixinsui would be good if you can pick up this userstory.

**Comment by baixinsui** [comment]
I will take it.

**Comment by baixinsui** [comment]
What is the `input` for verification? the variables inputted by the user ?

**Comment by swaroopar** [comment]
@baixinsui thank you. 
The input to the evaluate policies API are the rego policy content and the terraform plan as json. We implemented a new API method in terraform-boot which returns only the plan json. We must use that before calling the evaluate method. 

Mostly for terraform-local we must implement something to get the terraform plan as json.

**Comment by baixinsui** [comment]
@swaroopar Ok. I will add a same method in terraform-local to get the terraform plan as json, and then use the json and all enabled policies as the input to call the   evaluate policies API
