### ISSUE TITLE
update service deployment alert

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#975]
- [ ] replace 'RequestID" -> Service ID
- [ ] provide copy option to Service ID
- [ ] Also make it a link that redirects to MyService with the service filtered. 

![image](https://github.com/eclipse-xpanse/xpanse/assets/54129659/a5dba1fa-3dda-42e3-97aa-af78e0212e6e)

**Comment by WangLiNaruto** [comment]
let me do it
