### ISSUE TITLE
Add dashboard to MyServices link

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#983]
- [x] Make each of the numbers in the dashboard clickable - on mouse hover, it must clearly visible that they are clickable. 
- [x] On click - the page must be directed to MyServices component and the URL must be updated to "serviceState=xxxx" with the corresponding state updated. 
- [x] Table must be filtered and the filtered value must be selected in the drop down.

**Comment by Alice1319** [comment]
I‘ll take this
