### ISSUE TITLE
remove userId from ServiceVo

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#991]
The ServiceVo datamodel has userId field which must not be returned. This ID is also an internal ID of identity system and hence has no value in this response. 

https://github.com/eclipse-xpanse/xpanse/blob/8d06182c2b74fc77248b55db3fd5c0bf5ab50ed6/modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/ServiceVo.java#L36

**Comment by baixinsui** [comment]
Do we need to remove the userId from all view object?

**Comment by swaroopar** [comment]
@baixinsui yes we can remove it from everywhere.

**Comment by baixinsui** [comment]
I will fix it.
