### ISSUE TITLE
Create simple dashboard for ISV user

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#993]
Similar to the dashboard of end user, we need simple dashboard for ISV users with the following information 

- [ ] Total number of services offered by the ISV
- [ ] Total number of currently successfully deployed services of the ISV - This information can be obtained using the service that will be implemented in https://github.com/eclipse-xpanse/xpanse/issues/992

**Comment by Alice1319** [comment]
I'll take this
